import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';

type MetricRow = {
  metric_id: string;
  metric_label: string;
  numeric_value: string | null;
  display_value: string;
  unit: string;
  source_status: string;
  from_sys_id: string;
  as_of_date: string;
  load_history_id: string;
  provenance_json: Record<string, unknown>;
};

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW — do not hand-edit.
 * Kentucky operational public-source aggregates (LoadClass=REAL).
 */
export const KY_OPERATIONAL_SOURCES = ${JSON.stringify(payload, null, 2)};
`;
}

function generatedRecoveryModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW — do not hand-edit.
 * Kentucky recovery-reconciliation review package (LoadClass=REAL).
 */
export const KY_RECOVERY_RECONCILIATION = ${JSON.stringify(payload, null, 2)};

export function recoveryReconciliationTotals(rows = KY_RECOVERY_RECONCILIATION.rows) {
  return rows.reduce((totals, row) => {
    totals.reportedCandidate += Number(row.reportedCandidate) || 0;
    if (row.disposition === 'recovered') totals.confirmedRecovered += Number(row.recoveredAmount) || 0;
    if (row.disposition === 'outstanding') totals.confirmedOutstanding += Number(row.reportedCandidate) || 0;
    if (row.disposition === 'awaiting-evidence') totals.awaitingEvidence += 1;
    return totals;
  }, { reportedCandidate: 0, confirmedRecovered: 0, confirmedOutstanding: 0, awaitingEvidence: 0 });
}
`;
}

export class ExportKentuckyOperationalSourcesForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  MetricCount = 0;
  SourceCount = 0;
  ExportPath = config.operationalSourcesExportPath;

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `WITH latest_source_load AS (
           SELECT DISTINCT ON (d.from_sys_id) d.from_sys_id, h.load_history_id
           FROM bw_ctl.load_history h
           JOIN bw_ctl.data_request d USING (data_request_id)
           WHERE h.load_class='REAL' AND h.status='SUCCEEDED'
             AND d.from_sys_id IN ('CMS_MCPAR','CMS_PROVIDER_DATA','HHS_OIG_LEIE','USA_SPENDING',
               'KY_OPEN_GIS','KY_OSBD_BUDGET','KY_DMS_MCO_CONTRACTS','KY_TRANSPARENCY_SPEND')
             -- USA_SPENDING is also written by the OFR-01 award-grain molecule under a
             -- different data_request_id; only the KY fiscal-year molecule's loads back
             -- these operational-source metrics, so pin to that request explicitly.
             AND (d.from_sys_id <> 'USA_SPENDING' OR d.data_request_id = 'DR-REAL-USASPENDING-KY-MEDICAID')
           ORDER BY d.from_sys_id, COALESCE(h.completed_at,h.started_at) DESC, h.load_history_id DESC
         )
         SELECT m.metric_id, m.metric_label, m.numeric_value::text, m.display_value, m.unit,
           m.source_status, m.from_sys_id, m.as_of_date::text, m.load_history_id, m.provenance_json
         FROM bw_cube.cube_operational_source_metric m
         JOIN latest_source_load l ON l.from_sys_id=m.from_sys_id AND l.load_history_id=m.load_history_id
         ORDER BY m.from_sys_id,m.metric_id`,
      );
      const loads = await this.client.query<{
        from_sys_id: string;
        load_history_id: string;
        source_uri: string;
        status: string;
        row_count: number;
        content_hash: string;
        as_of_date: string;
        notes: string;
      }>(
        `SELECT DISTINCT ON (oi.from_sys_id)
           oi.from_sys_id, h.load_history_id, h.source_uri, h.status,
           COALESCE(h.row_count,0)::int AS row_count, COALESCE(h.content_hash,'') AS content_hash,
           h.as_of_date::text, COALESCE(h.notes,'') AS notes
         FROM bw_psa_meta.object_index oi
         JOIN bw_ctl.load_history h ON h.load_history_id=oi.load_history_id
         WHERE oi.load_class='REAL'
           AND h.status='SUCCEEDED'
           AND oi.from_sys_id IN ('CMS_MCPAR','CMS_PROVIDER_DATA','HHS_OIG_LEIE','USA_SPENDING',
             'KY_OPEN_GIS','KY_OSBD_BUDGET','KY_DMS_MCO_CONTRACTS','KY_TRANSPARENCY_SPEND')
           AND (oi.from_sys_id <> 'USA_SPENDING' OR h.data_request_id = 'DR-REAL-USASPENDING-KY-MEDICAID')
         ORDER BY oi.from_sys_id, COALESCE(h.completed_at,h.started_at) DESC`,
      );
      const documents = await this.client.query<{
        document_id: string; title: string; document_uri: string; media_type: string;
        byte_length: number; content_hash: string; publication_period: string;
        document_status: string; from_sys_id: string; as_of_date: string;
      }>(
        `SELECT DISTINCT ON (d.document_id)
           d.document_id,d.title,d.document_uri,d.media_type,d.byte_length,d.content_hash,
           d.publication_period,d.document_status,d.from_sys_id,d.as_of_date::text
         FROM bw_dso.dso_public_document d
         JOIN bw_ctl.load_history h ON h.load_history_id=d.load_history_id
         WHERE d.load_class='REAL' AND h.status='SUCCEEDED'
         ORDER BY d.document_id, COALESCE(h.completed_at,h.started_at) DESC`,
      );
      const recoveryRows = await this.client.query<{
        reporting_entity: string; reporting_period_start: string; reporting_period_end: string;
        reported_candidate: string; premium_revenue: string; load_history_id: string;
      }>(
        `WITH latest AS (
           SELECT load_history_id
           FROM bw_ctl.load_history h
           JOIN bw_ctl.data_request d USING (data_request_id)
           WHERE h.load_class='REAL' AND h.status='SUCCEEDED' AND d.from_sys_id='CMS_MCPAR'
           ORDER BY COALESCE(h.completed_at,h.started_at) DESC LIMIT 1
         )
         SELECT reporting_entity, reporting_period_start::text, reporting_period_end::text,
           MAX(response_text::numeric) FILTER (WHERE question_id='plan_overpaymentReportingToStateDollarAmount')::text AS reported_candidate,
           MAX(response_text::numeric) FILTER (WHERE question_id='plan_overpaymentReportingToStateCorrespondingYearPremiumRevenue')::text AS premium_revenue,
           r.load_history_id
         FROM bw_dso.dso_mcpar_response r JOIN latest l USING (load_history_id)
         WHERE question_id IN ('plan_overpaymentReportingToStateDollarAmount','plan_overpaymentReportingToStateCorrespondingYearPremiumRevenue')
           AND reporting_entity<>''
         GROUP BY reporting_entity,reporting_period_start,reporting_period_end,r.load_history_id
         HAVING MAX(response_text) FILTER (WHERE question_id='plan_overpaymentReportingToStateDollarAmount') IS NOT NULL
         ORDER BY reporting_entity`,
      );
      const authorityRows = await this.client.query<{ question_id: string; response_text: string }>(
        `WITH latest AS (
           SELECT load_history_id FROM bw_ctl.load_history h JOIN bw_ctl.data_request d USING (data_request_id)
           WHERE h.load_class='REAL' AND h.status='SUCCEEDED' AND d.from_sys_id='CMS_MCPAR'
           ORDER BY COALESCE(h.completed_at,h.started_at) DESC LIMIT 1
         )
         SELECT question_id,response_text FROM bw_dso.dso_mcpar_response r JOIN latest l USING (load_history_id)
         WHERE question_id IN ('state_overpaymentStandard','state_overpaymentStandardContractLanguageLocation','state_overpaymentStandardDescription','state_overpaymentReportingMonitoringEfforts')`,
      );

      const metricRows = metrics.rows.map((row) => ({
        metricId: row.metric_id,
        label: row.metric_label,
        numericValue: row.numeric_value == null ? null : Number(row.numeric_value),
        displayValue: row.display_value,
        unit: row.unit,
        sourceStatus: row.source_status,
        fromSysId: row.from_sys_id,
        publisher: ({
          CMS_MCPAR: 'CMS',
          CMS_PROVIDER_DATA: 'CMS Provider Data',
          HHS_OIG_LEIE: 'HHS-OIG',
          USA_SPENDING: 'USAspending',
          KY_OPEN_GIS: 'Kentucky GeoNet',
          KY_OSBD_BUDGET: 'Kentucky OSBD',
          KY_DMS_MCO_CONTRACTS: 'Kentucky DMS',
          KY_TRANSPARENCY_SPEND: 'Kentucky Transparency',
        } as Record<string, string>)[row.from_sys_id] || row.from_sys_id,
        asOfDate: row.as_of_date,
        loadHistoryId: row.load_history_id,
        provenance: row.provenance_json,
      }));
      const sourceStatuses = loads.rows.map((row) => {
        const sourceMetrics = metricRows.filter((metric) => metric.fromSysId === row.from_sys_id);
        return {
          fromSysId: row.from_sys_id,
          status: sourceMetrics[0]?.sourceStatus || row.status,
          asOfDate: row.as_of_date,
          rowCount: row.row_count,
          sourceUri: row.source_uri,
          contentHash: row.content_hash,
          loadHistoryId: row.load_history_id,
          notes: row.notes,
        };
      });
      const byId = new Map(metricRows.map((metric) => [metric.metricId, metric]));
      const authority = new Map(authorityRows.rows.map((row) => [row.question_id, row.response_text]));
      const mcparLoad = loads.rows.find((row) => row.from_sys_id === 'CMS_MCPAR');
      const recoveryReconciliation = {
        schema: 'decisionpro/ky-recovery-reconciliation/v1',
        state: 'KY',
        reportingPeriod: {
          start: recoveryRows.rows[0]?.reporting_period_start || '',
          end: recoveryRows.rows[0]?.reporting_period_end || '',
          label: `CY ${String(recoveryRows.rows[0]?.reporting_period_end || '').slice(0, 4)}`,
        },
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        source: {
          publisher: 'Centers for Medicare & Medicaid Services',
          title: 'Managed Care Program Annual Report Public Use File 2024',
          uri: mcparLoad?.source_uri || config.mcparCsvUri,
          contentHash: mcparLoad?.content_hash || '',
          loadHistoryId: recoveryRows.rows[0]?.load_history_id || '',
          amountQuestionId: 'plan_overpaymentReportingToStateDollarAmount',
          premiumQuestionId: 'plan_overpaymentReportingToStateCorrespondingYearPremiumRevenue',
        },
        authority: {
          standard: authority.get('state_overpaymentStandard') || '',
          contractLocation: authority.get('state_overpaymentStandardContractLanguageLocation') || '',
          summary: authority.get('state_overpaymentStandardDescription') || '',
          monitoring: authority.get('state_overpaymentReportingMonitoringEfforts') || '',
        },
        completionBoundary: 'DecisionPro has prepared the public-source portion of the reconciliation. Final recovery classification requires an authorized aggregate or plan-level PI-06, PI-02, CP-06, recovery-ledger, or payment extract. Do not upload PHI or person-level records.',
        planningEstimate: {
          estimateType: 'Planning sensitivity range; not a recovery forecast',
          lowRecoveryRate: 0.10,
          planningRecoveryRate: 0.25,
          highRecoveryRate: 0.50,
          reviewHoursPerPlanLow: 12,
          reviewHoursPerPlanHigh: 20,
          loadedHourlyCostLow: 60,
          loadedHourlyCostHigh: 80,
          elapsedWeeksLow: 3,
          elapsedWeeksHigh: 6,
          justification: 'No public Kentucky recovery-rate series is available in the governed sources. DecisionPro therefore uses transparent 10%, 25%, and 50% sensitivity cases across the reported candidate pool, plus six plans at 12–20 review hours each and a $60–$80 assumed loaded hourly cost. Replace these assumptions with DMS historical recovery and staffing data when authorized.',
        },
        rows: recoveryRows.rows.map((row) => {
          const reportedCandidate = Number(row.reported_candidate);
          const premiumRevenue = Number(row.premium_revenue);
          return {
            id: row.reporting_entity.split(/\s+/)[0].toLowerCase().replace(/[^a-z0-9]/g, ''),
            plan: row.reporting_entity,
            reportedCandidate,
            premiumRevenue,
            candidateShareOfPremium: premiumRevenue > 0 ? reportedCandidate / premiumRevenue : 0,
            evidenceStatus: 'Awaiting authorized recovery record',
            disposition: 'awaiting-evidence', recoveredAmount: '', evidenceReference: '', reviewerNotes: '',
          };
        }),
      };
      const actions = [
        {
          actionId: 'KY-ACTION-ENCOUNTER-REMEDIATION',
          domain: 'Managed-care data reliability',
          title: 'Prioritize encounter-data remediation review',
          signal: `Lowest plan-reported encounter timeliness is ${byId.get('ky-mcpar-min-encounter-timeliness')?.displayValue || 'not available'}.`,
          nextAction: 'Select the aligned encounter-data questions, validate reporting entity and denominator, bind the effective contract clause, assign a corrected-file due date, and reconcile the resubmission before releasing dependent measures.',
          owner: 'DMS data stewardship and MCO contract oversight',
          successMeasure: 'Accepted encounter-file rate, correction cycle time, and downstream measures released from data-quality hold.',
          guardrail: 'Annual state-reported MCPAR data is a triage signal, not evidence of contractual breach.',
          evidenceMetricIds: ['ky-mcpar-min-encounter-timeliness', 'ky-mcpar-rows', 'ky-mcpar-entities'],
        },
        {
          actionId: 'KY-ACTION-OVERPAYMENT-RECONCILIATION',
          domain: 'Program integrity',
          title: 'Reconcile plan-reported overpayment dollars',
          signal: `${byId.get('ky-mcpar-reported-overpayments')?.displayValue || 'No value'} is present in the aligned plan-reported overpayment field; this does not establish that the amount remains outstanding.`,
          nextAction: 'Filter the governed MCPAR rows to overpayment/recovery questions, reconcile each response to recovery status and contract authority, and open a case only for verified unresolved balances or repeat control failures.',
          owner: 'DMS program integrity and contract management',
          successMeasure: 'Candidate dollars reconciled, verified outstanding balance, recovery cycle time, and recurrence rate.',
          guardrail: 'Reported overpayments are not proof of waste or misconduct and may already be recovered.',
          evidenceMetricIds: ['ky-mcpar-reported-overpayments', 'ky-mcpar-overpayment-premium-ratio'],
        },
        {
          actionId: 'KY-ACTION-PROVIDER-QUALITY-ACCESS',
          domain: 'Provider quality and access',
          title: 'Validate low-rated facility and capacity combinations',
          signal: `${byId.get('ky-provider-low-rating')?.displayValue || 'No value'} facilities have a 1- or 2-star overall rating among ${byId.get('ky-provider-facilities')?.displayValue || 'the loaded facilities'}; ${byId.get('ky-hospital-counties')?.displayValue || 'county'} hospital-capacity coverage is available for validation.`,
          nextAction: 'Join facilities to county capacity, ownership, and verified exclusion records; route quality-plus-capacity risk combinations to human review.',
          owner: 'Provider enrollment, facility quality, and network oversight',
          successMeasure: 'Verified cases, unresolved county capacity gaps, remediation time, and post-remediation quality trend.',
          guardrail: 'CMS nursing-home data is Medicare-certified facility context, not Medicaid payment truth; fuzzy identity matches never support adverse action.',
          evidenceMetricIds: ['ky-provider-facilities', 'ky-provider-low-rating', 'ky-provider-beds', 'ky-leie-records', 'ky-hospital-counties'],
        },
        {
          actionId: 'KY-ACTION-BUDGET-VARIANCE',
          domain: 'Budget and contract intelligence',
          title: 'Establish a revision-aware budget and contract evidence room',
          signal: `${byId.get('ky-budget-documents')?.displayValue || 'Current'} budget and ${byId.get('ky-contract-documents')?.displayValue || 'current MCO'} contract files are indexed and content-hashed; the latest complete-year USAspending 93.778 obligation context is ${byId.get('ky-usaspending-latest-complete-fy')?.displayValue || 'available'}.`,
          nextAction: 'Extract page-cited appropriations and contract clauses into governed facts, then reconcile them to official state accounting exports when a supported feed or authorized extract is available.',
          owner: 'Budget/fiscal analysis and DMS contract management',
          successMeasure: 'Versioned provisions extracted, variance explanations resolved, actioned dollars, and benefit-realization follow-through.',
          guardrail: 'Federal obligations, appropriations, contract ceilings, encumbrances, and payments are different grains; variance alone is not inefficiency.',
          evidenceMetricIds: ['ky-budget-documents', 'ky-contract-documents', 'ky-usaspending-latest-complete-fy', 'ky-usaspending-current-partial-fy'],
        },
      ];
      const payload = {
        schema: 'decisionpro/ky-operational-sources/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        productState: 'KY',
        completionBoundary: 'Five analytical API/file sources are hydrated; two official document sets are indexed and downloaded with hashes; Kentucky Transparency is source-verified only because no supported analytical bulk API/export is published.',
        sourceCount: sourceStatuses.length,
        metricCount: metricRows.length,
        sourceStatuses,
        metrics: metricRows,
        documents: documents.rows.map((row) => ({
          documentId: row.document_id, title: row.title, uri: row.document_uri,
          mediaType: row.media_type, byteLength: row.byte_length, contentHash: row.content_hash,
          publicationPeriod: row.publication_period, status: row.document_status,
          fromSysId: row.from_sys_id, asOfDate: row.as_of_date,
        })),
        actions,
      };
      this.MetricCount = metricRows.length;
      this.SourceCount = sourceStatuses.length;
      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      await fs.mkdir(path.dirname(config.recoveryReconciliationExportPath), { recursive: true });
      await fs.writeFile(config.recoveryReconciliationExportPath, generatedRecoveryModule(recoveryReconciliation), 'utf8');
      const jsonPath = path.join(config.psaRoot, '..', 'exports', 'ky-operational-sources.json');
      await fs.mkdir(path.dirname(jsonPath), { recursive: true });
      await fs.writeFile(jsonPath, JSON.stringify(payload, null, 2), 'utf8');
      await fs.writeFile(path.join(config.psaRoot, '..', 'exports', 'ky-recovery-reconciliation.json'), JSON.stringify(recoveryReconciliation, null, 2), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
