import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config, REPO_ROOT } from '../config.js';
import { SOURCE_SYSTEMS } from '../catalog/seedCatalog.js';
import { readFixtureJson } from './SeedWarehouseCatalog.js';

const ALP = path.join(REPO_ROOT, 'wireframe V1', 'app', 'src', 'data', 'alp');
const DOCS_PLANNING = path.join(REPO_ROOT, 'docs', 'planning');

type AvailablePack = {
  note?: string;
  sources: Record<
    string,
    {
      publisher?: string;
      grain?: string;
      cadence?: string;
      availableDepth?: string;
      publicUris?: string[];
      seriesKind?: string;
      definitionBreakNotes?: string[];
      archiveProbe?: Array<{
        periodId: string;
        uri: string;
        httpStatus: number;
        parseStatus: string;
      }>;
    }
  >;
  measureConsumers?: Record<
    string,
    { rooms?: string[]; tiles?: string[]; findings?: string[] }
  >;
};

type Pack = {
  asOfDate: string;
  landingMeasures: Array<{
    measureId: string;
    asOfDate: string;
    fromSysId: string;
    periodId?: string;
    numericValue: number | null;
    displayValue: string;
  }>;
  gaps: Array<{
    gapId: string;
    title: string;
    need: string;
    rooms: string[];
    findingIds: string[];
    paidFollowOn: string;
  }>;
};

function writeJs(exportName: string, payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * Data Spectrum trust inventory (LoadClass=REAL gate).
 */
export const ${exportName} = ${JSON.stringify(payload, null, 2)};
`;
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))].sort();
}

/**
 * Business Action: ExportDataSpectrumForUi
 * Machine inventory of Available vs Loaded vs Used vs Gaps/Inconsistencies per FromSysID + Explicit Gaps.
 */
export class ExportDataSpectrumForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = path.join(ALP, 'dataSpectrum.js');
  MarkdownPath = path.join(DOCS_PLANNING, 'data-spectrum-latest.md');
  RowCount = 0;

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const available = await readFixtureJson<AvailablePack>('dataSpectrumAvailable.json');
      const pack = await readFixtureJson<Pack>('realPublicHydrationPack.json');

      const landing = await this.client.query<{
        measure_id: string;
        as_of_date: string;
        from_sys_id: string;
        numeric_value: string | null;
        display_value: string;
        provenance_json: { periodId?: string; periodYm?: string } | null;
      }>(
        `SELECT measure_id, as_of_date::text, from_sys_id, numeric_value::text, display_value, provenance_json
         FROM bw_cube.cube_exec_landing
         WHERE load_class = 'REAL'
         ORDER BY from_sys_id, measure_id, as_of_date`,
      );

      const bySys = new Map<string, typeof landing.rows>();
      for (const row of landing.rows) {
        const list = bySys.get(row.from_sys_id) || [];
        list.push(row);
        bySys.set(row.from_sys_id, list);
      }

      const gapsQ = await this.client.query<{
        gap_id: string;
        title: string;
        need: string;
        rooms: string[];
        finding_ids: string[];
        paid_follow_on: string;
      }>(`SELECT gap_id, title, need, rooms, finding_ids, paid_follow_on FROM bw_ctl.gap_object ORDER BY gap_id`);

      const sourceRows = SOURCE_SYSTEMS.filter((s) => s.from_sys_id !== 'TEST_FIXTURE_PACK').map((s) => {
        const meta = available.sources[s.from_sys_id] || {};
        const loaded = bySys.get(s.from_sys_id) || [];
        const measureIds = uniqueSorted(loaded.map((r) => r.measure_id));
        const asOfDates = uniqueSorted(loaded.map((r) => r.as_of_date));
        const periodIds = uniqueSorted(
          loaded.map((r) => r.provenance_json?.periodId || r.provenance_json?.periodYm || '').filter(Boolean),
        );
        const consumers = measureIds.flatMap((mid) => {
          const c = available.measureConsumers?.[mid];
          return c
            ? [
                ...(c.rooms || []).map((r) => `room:${r}`),
                ...(c.tiles || []).map((t) => `tile:${t}`),
                ...(c.findings || []).map((f) => `finding:${f}`),
              ]
            : [];
        });

        const inconsistencies: string[] = [...(meta.definitionBreakNotes || [])];
        if (meta.archiveProbe?.length) {
          for (const probe of meta.archiveProbe) {
            if (probe.parseStatus === 'NOT_FOUND') {
              inconsistencies.push(
                `Archive PDF ${probe.periodId} HTTP ${probe.httpStatus} — not loaded (${probe.uri})`,
              );
            } else if (probe.parseStatus !== 'LOADED') {
              inconsistencies.push(
                `Archive PDF ${probe.periodId} parseStatus=${probe.parseStatus} (${probe.uri})`,
              );
            }
          }
        }
        if (s.from_sys_id === 'CMS_MEDICAID_PHARMACY' && measureIds.includes('M-017') && asOfDates.length < 2) {
          inconsistencies.push(
            'CMS Spending by Drug publishes ~5 national year columns; KY curated pack currently binds one annual aggregate — not a synthetic multi-year KY stretch.',
          );
        }
        if (s.from_sys_id === 'CMS_MEDICAID_SCORECARD') {
          const years = uniqueSorted(
            pack.landingMeasures
              .filter((m) => m.fromSysId === 'CMS_MEDICAID_SCORECARD')
              .map((m) => m.asOfDate.slice(0, 4)),
          );
          if (!years.includes('2024')) {
            inconsistencies.push('Core Set 2024 public CSV URI not available at last research scan (HTTP 404).');
          }
          const wcvYears = pack.landingMeasures
            .filter((m) => m.measureId === 'M-010')
            .map((m) => m.asOfDate.slice(0, 4));
          if (!wcvYears.includes('2020')) {
            inconsistencies.push('WCV-CH definition/vintage gap: abbreviation absent from 2020 Core Set CSV.');
          }
        }

        const blockReason =
          'block_reason' in s ? String((s as { block_reason?: string }).block_reason || '') : '';
        const unblockNeed =
          'unblock_need' in s ? String((s as { unblock_need?: string }).unblock_need || '') : '';

        let disposition: 'LOADED' | 'CATALOGUED' | 'BLOCKED' = 'CATALOGUED';
        if (s.tos_grade === 'RESTRICTED' || s.tos_grade === 'OUT_OF_POC' || blockReason) {
          disposition = 'BLOCKED';
        } else if (
          loaded.length > 0 ||
          s.from_sys_id === 'CMS_DATA_MEDICAID_ENR' ||
          s.from_sys_id === 'KY_DMS_MCO_CONTRACTS'
        ) {
          disposition = 'LOADED';
        }

        let nextAction = s.paid_follow_on_todo || '';
        if (disposition === 'CATALOGUED' && !nextAction) {
          nextAction = 'Director-authorize curated extract or Data Request bind';
        }
        if (disposition === 'BLOCKED') {
          nextAction = unblockNeed || nextAction || 'Obtain license/DUA then Director-authorize REAL load';
        }

        return {
          kind: 'source' as const,
          fromSysId: s.from_sys_id,
          publisher: s.publisher,
          tosGrade: s.tos_grade,
          disposition,
          provides: {
            publisher: meta.publisher || s.publisher,
            grain: meta.grain || '',
            cadence: meta.cadence || '',
            publicUris: meta.publicUris || [s.base_uri],
            tosGrade: s.tos_grade,
            seriesKind: meta.seriesKind || 'unknown',
          },
          availableDepth: meta.availableDepth || s.attribution_notes,
          loadedDepth: {
            measureIds,
            asOfDates,
            periodIds,
            rowCount: loaded.length,
            earliestAsOf: asOfDates[0] || null,
            latestAsOf: asOfDates[asOfDates.length - 1] || null,
          },
          howUsed: {
            measureIds,
            consumers: uniqueSorted(consumers),
          },
          inconsistencies,
          nextAction,
          blockReason: blockReason || undefined,
        };
      });

      // Ensure enrollment shows loaded even when cube rows exist under CMS_DATA_MEDICAID_ENR
      for (const row of sourceRows) {
        if (row.fromSysId === 'CMS_DATA_MEDICAID_ENR' || row.fromSysId === 'KY_DMS_MCO_CONTRACTS') {
          row.disposition = 'LOADED';
        }
      }

      const gapRows = gapsQ.rows.map((g) => ({
        kind: 'gap' as const,
        fromSysId: g.gap_id,
        publisher: 'Explicit Gap',
        tosGrade: 'GAP',
        disposition: 'GAP' as const,
        provides: {
          publisher: 'Not publicly fillable',
          grain: 'n/a',
          cadence: 'n/a',
          publicUris: [],
          tosGrade: 'GAP',
          seriesKind: 'none',
        },
        availableDepth: 'No continuous public series — requires authorized feed / DUA / license.',
        loadedDepth: {
          measureIds: [],
          asOfDates: [],
          periodIds: [],
          rowCount: 0,
          earliestAsOf: null,
          latestAsOf: null,
        },
        howUsed: {
          measureIds: [],
          consumers: uniqueSorted([
            ...g.rooms.map((r) => `room:${r}`),
            ...g.finding_ids.map((f) => `finding:${f}`),
          ]),
        },
        inconsistencies: [`Gap remains unlabeled as history: ${g.title}`],
        nextAction: g.paid_follow_on,
        title: g.title,
        need: g.need,
      }));

      const rows = [...sourceRows, ...gapRows];
      this.RowCount = rows.length;

      const loadedSources = sourceRows.filter((r) => r.disposition === 'LOADED').length;
      const cataloguedSources = sourceRows.filter((r) => r.disposition === 'CATALOGUED').length;
      const blockedSources = sourceRows.filter((r) => r.disposition === 'BLOCKED').length;
      const allAsOf = uniqueSorted(landing.rows.map((r) => r.as_of_date));

      const payload = {
        schema: 'decisionpro/data-spectrum/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        product: 'DecisionPro',
        note:
          'Machine-exported Data Spectrum — Available (SoT research) vs Loaded (this gate) vs Used vs Inconsistencies. Not hand-written prose.',
        availableNote: available.note || '',
        summary: {
          sourcesLoaded: loadedSources,
          sourcesCatalogued: cataloguedSources,
          sourcesBlocked: blockedSources,
          explicitGaps: gapRows.length,
          earliestRealAsOf: allAsOf[0] || null,
          latestRealAsOf: allAsOf[allAsOf.length - 1] || null,
          landingRowCount: landing.rows.length,
          gateTimestamp: new Date().toISOString(),
        },
        rows,
      };

      await fs.mkdir(ALP, { recursive: true });
      await fs.writeFile(this.ExportPath, writeJs('DATA_SPECTRUM', payload), 'utf8');

      const md = renderMarkdown(payload);
      await fs.mkdir(DOCS_PLANNING, { recursive: true });
      await fs.writeFile(this.MarkdownPath, md, 'utf8');

      const jsonSide = path.join(config.psaRoot, '..', 'exports', 'data-spectrum.json');
      await fs.mkdir(path.dirname(jsonSide), { recursive: true });
      await fs.writeFile(jsonSide, JSON.stringify(payload, null, 2), 'utf8');

      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }
}

function renderMarkdown(payload: {
  generatedAt: string;
  summary: Record<string, unknown>;
  rows: Array<Record<string, unknown>>;
}): string {
  const s = payload.summary;
  const lines = [
    '# Data Spectrum (latest gate export)',
    '',
    `Generated: ${payload.generatedAt}`,
    '',
    '## Summary',
    '',
    `- Sources loaded: ${s.sourcesLoaded}`,
    `- Sources catalogued: ${s.sourcesCatalogued}`,
    `- Sources blocked: ${s.sourcesBlocked}`,
    `- Explicit gaps: ${s.explicitGaps}`,
    `- REAL as-of window: ${s.earliestRealAsOf || '—'} → ${s.latestRealAsOf || '—'}`,
    `- Landing cube rows: ${s.landingRowCount}`,
    '',
    '## Inventory',
    '',
  ];
  for (const row of payload.rows) {
    const id = String(row.fromSysId);
    const disp = String(row.disposition);
    const available = String(row.availableDepth || '');
    const loaded = row.loadedDepth as { rowCount?: number; earliestAsOf?: string; latestAsOf?: string };
    const inconsist = (row.inconsistencies as string[]) || [];
    lines.push(`### ${id} — ${disp}`);
    lines.push('');
    lines.push(`- **Available:** ${available}`);
    lines.push(
      `- **Loaded:** ${loaded.rowCount || 0} rows${
        loaded.earliestAsOf ? ` (${loaded.earliestAsOf} → ${loaded.latestAsOf})` : ''
      }`,
    );
    if (inconsist.length) {
      lines.push(`- **Inconsistencies:** ${inconsist.join('; ')}`);
    }
    lines.push(`- **Next:** ${row.nextAction || '—'}`);
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}
