import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckSubawardFlowGraphNumbers } from './CheckSubawardFlowGraphNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type EdgeRow = { state_code: string; source_org: string; recipient_org: string; amount: string | null; action_date: string | null; assistance_listing: string; identity_confidence: string; recipient_ein: string | null };

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-06 federal sub-award flow graph, state-neutral (KY + FL).
 * Every edge carries an explicit identity_confidence — exact-derived or
 * unresolved — never silently treated as confirmed.
 */
export const SUBAWARD_FLOW_GRAPH = ${JSON.stringify(payload, null, 2)};
`;
}

const EDGE_CAP = 25;

/**
 * Business Action: ExportSubawardFlowGraphForUi
 * Exports per-state funding-concentration and program-overlap metrics plus
 * a bounded, identity-confidence-labeled funding-edge list.
 */
export class ExportSubawardFlowGraphForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.subawardFlowGraphExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_subaward_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const edges = await this.client.query<EdgeRow>(
        `SELECT state_code, source_org, recipient_org, amount::text, action_date::text, assistance_listing, identity_confidence, recipient_ein
         FROM bw_dso.dso_funding_edge WHERE load_class='REAL' ORDER BY amount DESC NULLS LAST`,
      );

      const check = new CheckSubawardFlowGraphNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        const stateEdges = edges.rows.filter((e) => e.state_code === state);
        byState[state] = {
          state,
          identityConfidenceNote: 'Every edge below is labeled exact-derived (the sub-recipient name exactly matched an OFR-02 crosswalk identity record) or unresolved (no match). Concentration and overlap metrics are computed only from exact-derived edges where noted; unresolved edges are never silently treated as confirmed identity.',
          metrics: stateMetrics,
          fundingEdges: {
            note: 'Sub-award funding edges — a funding-flow map, never itself evidence of duplication, waste, or improper coordination.',
            edges: stateEdges.slice(0, EDGE_CAP).map((e) => ({
              sourceOrg: e.source_org, recipientOrg: e.recipient_org,
              amount: e.amount == null ? null : Number(e.amount), actionDate: e.action_date,
              assistanceListing: e.assistance_listing, identityConfidence: e.identity_confidence,
              recipientEin: e.recipient_ein,
            })),
          },
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/subaward-flow-graph/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        scope: 'USAspending subawards for the OFR-01 KY+FL prime-award universe',
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
