import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckFederalAwardGrainNumbers } from './CheckFederalAwardGrainNumbers.js';

type MetricRow = {
  metric_id: string; state_code: string; metric_label: string; numeric_value: string | null;
  display_value: string; unit: string; as_of_date: string; provenance_json: Record<string, unknown>;
};

type AwardRow = {
  state_code: string; assistance_listing: string; award_id_display: string; recipient_name: string;
  recipient_uei: string; award_amount: string | null; period_of_performance_start: string | null;
  period_of_performance_end: string | null; awarding_agency: string; location_filter: string;
};

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-01 federal award/recipient-grain (USAspending), state-neutral (KY + FL).
 * Each state key is populated only from that state's own hydration — never
 * cross-populated from the other state's rows.
 */
export const FEDERAL_AWARD_GRAIN = ${JSON.stringify(payload, null, 2)};
`;
}

/**
 * Business Action: ExportFederalAwardGrainForUi
 * Exports per-state award-grain metrics, the federal funding cliff calendar
 * slice, and single-stream-dependency review candidates. Runs its own
 * Source Reconciliation pass so the exported payload always carries a fresh
 * claimAllowed flag.
 */
export class ExportFederalAwardGrainForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.federalAwardGrainExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label,
           numeric_value::text, display_value, unit, as_of_date::text, provenance_json
         FROM bw_cube.cube_federal_award_metric
         WHERE load_class='REAL'
         ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const awards = await this.client.query<AwardRow>(
        `SELECT state_code, assistance_listing, award_id_display, recipient_name, recipient_uei,
           award_amount::text, period_of_performance_start::text, period_of_performance_end::text,
           awarding_agency, location_filter
         FROM bw_dso.dso_federal_award
         WHERE load_class='REAL'
         ORDER BY state_code, award_amount DESC NULLS LAST`,
      );

      const check = new CheckFederalAwardGrainNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = metrics.rows.filter((m) => m.state_code === state);
        const stateAwards = awards.rows.filter((a) => a.state_code === state);
        const byId = Object.fromEntries(stateMetrics.map((m) => [m.metric_id, {
          label: m.metric_label,
          numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
          displayValue: m.display_value,
          unit: m.unit,
          asOfDate: m.as_of_date,
          provenance: m.provenance_json,
        }]));
        byState[state] = {
          state,
          metrics: byId,
          fundingCliffCalendar: {
            note: 'Awards with a published period-of-performance end date within the review window. A listed expiration is a renewal-review prompt, not a predicted funding lapse.',
            buckets: ['0-6mo', '6-12mo', '12-24mo'].map((bucketId) => ({
              bucketId,
              count: byId[`ofr-award-cliff-${bucketId}-count`]?.numericValue ?? 0,
              amount: byId[`ofr-award-cliff-${bucketId}-amount`]?.numericValue ?? 0,
              displayAmount: byId[`ofr-award-cliff-${bucketId}-amount`]?.displayValue ?? '$0',
            })),
          },
          singleStreamDependency: {
            note: 'Review candidates only: recipients whose only tracked assistance-listing award in this window falls under one program. Not evidence the recipient lacks other funding.',
            recipientCount: byId['ofr-award-single-stream-recipients']?.numericValue ?? 0,
            amount: byId['ofr-award-single-stream-amount']?.numericValue ?? 0,
          },
          awards: stateAwards.map((a) => ({
            assistanceListing: a.assistance_listing,
            awardId: a.award_id_display,
            recipientName: a.recipient_name,
            recipientUei: a.recipient_uei || null,
            awardAmount: a.award_amount == null ? null : Number(a.award_amount),
            periodStart: a.period_of_performance_start,
            periodEnd: a.period_of_performance_end,
            awardingAgency: a.awarding_agency,
            locationFilter: a.location_filter,
          })),
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/federal-award-grain/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        assistanceListings: config.ofrAssistanceListings,
        reconciliation: {
          status: this.ReconciliationStatus,
          claimAllowed: this.ReconciliationStatus === 'PASS',
          checks: check.Results,
        },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
