import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckFacilityDistressNumbers } from './CheckFacilityDistressNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type FacilityRow = {
  ccn: string; facility_type: string; report_year: string; facility_name: string; state_code: string; county: string;
  number_of_beds: string | null; net_income: string | null; total_income: string | null;
  total_days_medicaid: string | null; total_days_all: string | null; uncompensated_care: string | null;
};
type CountyRow = { state_code: string; county: string; facility_count: string; low_margin_facility_count: string; total_beds: string | null; avg_medicaid_day_share: string | null; total_uncompensated_care: string | null };

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-04 CMS HCRIS Hospital + SNF facility financial distress, state-neutral (KY + FL).
 * Every value is Medicare-cost-report basis, not Medicaid payment truth.
 */
export const FACILITY_FINANCIAL_DISTRESS = ${JSON.stringify(payload, null, 2)};
`;
}

const WATCHLIST_CAP = 15;

/**
 * Business Action: ExportFacilityDistressForUi
 * Exports per-state facility-distress summary metrics, a bounded
 * negative-margin review-candidate list, and county-level rollups. Florida's
 * slice explicitly cites GAP-FL-F-14-PARAMETERS so this federal layer is
 * never mistaken for a replacement of the state's own blocked source.
 */
export class ExportFacilityDistressForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.facilityDistressExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_facility_distress_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const facilities = await this.client.query<FacilityRow>(
        `SELECT ccn, facility_type, report_year, facility_name, state_code, county, number_of_beds::text,
           net_income::text, total_income::text, total_days_medicaid::text, total_days_all::text, uncompensated_care::text
         FROM bw_dso.dso_facility_cost_report WHERE load_class='REAL'`,
      );
      const counties = await this.client.query<CountyRow>(
        `SELECT state_code, county, facility_count::text, low_margin_facility_count::text, total_beds::text,
           avg_medicaid_day_share::text, total_uncompensated_care::text
         FROM bw_dso.dso_county_facility_rollup WHERE load_class='REAL'`,
      );

      const check = new CheckFacilityDistressNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        const stateFacilities = facilities.rows.filter((f) => f.state_code === state);
        const negativeMargin = stateFacilities
          .map((f) => {
            const income = f.net_income == null ? null : Number(f.net_income);
            const total = f.total_income == null ? null : Number(f.total_income);
            const margin = income != null && total ? income / total : null;
            return { ...f, margin };
          })
          .filter((f) => f.margin != null && f.margin < 0)
          .sort((a, b) => a.margin! - b.margin!);

        byState[state] = {
          state,
          basisNote: 'Every value below is Medicare cost-report basis (CMS HCRIS annual filing), not Medicaid payment truth and not a full-payer financial statement.',
          floridaFallbackNote: state === 'FL'
            ? "Florida's own AHCA hospital-financial KPI export (dataset F-14) remains blocked at the publisher (GAP-FL-F-14-PARAMETERS: the Tableau view requires parameters and the permitted default export is empty). This CMS HCRIS layer is an explicitly labeled federal fallback alongside that gap, not a replacement for it."
            : null,
          metrics: stateMetrics,
          negativeMarginWatchlist: {
            note: 'Facility-years with a negative total margin this run — a continuity-review prompt, never a closure prediction or finding of distress.',
            facilities: negativeMargin.slice(0, WATCHLIST_CAP).map((f) => ({
              ccn: f.ccn, facilityType: f.facility_type, facilityName: f.facility_name, reportYear: f.report_year, county: f.county,
              totalMargin: f.margin == null ? null : Number(f.margin.toFixed(3)),
              medicaidDayShare: f.total_days_medicaid && f.total_days_all ? Number((Number(f.total_days_medicaid) / Number(f.total_days_all)).toFixed(3)) : null,
              uncompensatedCare: f.uncompensated_care == null ? null : Number(f.uncompensated_care),
            })),
          },
          countyRollups: {
            note: 'County-level facility counts and negative-margin counts — a closure-risk review watchlist, never a closure prediction. Not yet joined to eligible-population ratios (would require Census/HRSA data not wired into this package); documented scope boundary.',
            counties: counties.rows.filter((c) => c.state_code === state).map((c) => ({
              county: c.county, facilityCount: Number(c.facility_count), lowMarginFacilityCount: Number(c.low_margin_facility_count),
              totalBeds: c.total_beds == null ? null : Number(c.total_beds),
              avgMedicaidDayShare: c.avg_medicaid_day_share == null ? null : Number(c.avg_medicaid_day_share),
              totalUncompensatedCare: c.total_uncompensated_care == null ? null : Number(c.total_uncompensated_care),
            })).sort((a, b) => b.lowMarginFacilityCount - a.lowMarginFacilityCount),
          },
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/facility-financial-distress/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        sourceBasis: 'Medicare cost-report basis (CMS HCRIS), not Medicaid payment truth',
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
