import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckProgramHorizonEventsNumbers } from './CheckProgramHorizonEventsNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type EventRow = {
  state_code: string; event_type: string; scope: string; program: string; event_date: string;
  event_date_kind: string; status: string; detail: string; source_document_uri: string; retrieved_at: string;
};

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-07 waiver & grant horizon watch, state-neutral (KY + FL).
 * Every event carries a published date/status, a source_document_uri, and a
 * retrieved_at timestamp — never a predicted renewal outcome.
 */
export const PROGRAM_HORIZON_EVENTS = ${JSON.stringify(payload, null, 2)};
`;
}

const EVENT_CAP = 200;

/**
 * Grants.gov NOFO events are retrieved one query per OFR assistance listing
 * (RetrieveAndLoadProgramHorizonEvents queries `cfda: listing.code`) and land
 * with `program` = that listing's configured title. Mapping the title back to
 * its code is therefore a deterministic replay of the loader's own query key,
 * not a new inference — it restores the join key the OFR-07 table omitted so
 * an expiring award and a published successor opportunity can be paired.
 */
const LISTING_CODE_BY_TITLE = new Map<string, string>(
  config.ofrAssistanceListings.map((listing) => [listing.title, listing.code]),
);

/**
 * Business Action: ExportProgramHorizonEventsForUi
 * Exports per-state horizon-event lists (waiver expirations/milestones,
 * NOFO opportunities) plus summary metrics, sorted by event date.
 */
export class ExportProgramHorizonEventsForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.programHorizonEventsExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_program_horizon_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const events = await this.client.query<EventRow>(
        `SELECT state_code, event_type, scope, program, event_date::text, event_date_kind, status, detail, source_document_uri, retrieved_at::text
         FROM bw_dso.dso_program_horizon_event WHERE load_class='REAL' ORDER BY event_date ASC`,
      );

      const check = new CheckProgramHorizonEventsNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        const stateEvents = events.rows.filter((e) => e.state_code === state);
        byState[state] = {
          state,
          note: 'Every event below is a published date and status, cited to its source document and retrieval date — never a predicted renewal outcome. A nofo_opportunity event is national in scope (Grants.gov), not Kentucky/Florida eligibility-verified.',
          metrics: stateMetrics,
          events: {
            note: 'Waiver expiration/milestone events and open NOFO opportunities, soonest first.',
            items: stateEvents.slice(0, EVENT_CAP).map((e) => ({
              eventType: e.event_type, scope: e.scope, program: e.program, eventDate: e.event_date,
              eventDateKind: e.event_date_kind, status: e.status, detail: e.detail,
              sourceDocumentUri: e.source_document_uri, retrievedAt: e.retrieved_at,
              assistanceListing: e.event_type === 'nofo_opportunity' ? (LISTING_CODE_BY_TITLE.get(e.program) ?? null) : null,
            })),
          },
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/program-horizon-events/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        scope: 'CMS Section 1115 demonstration pages (KY TEAMKY, FL MMA) + Grants.gov search2 API for the OFR-01 assistance-listing set',
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
