import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckOwnershipNetworkNumbers } from './CheckOwnershipNetworkNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type ChainRow = { state_code: string; owner_organization_name: string; facility_count: string; total_beds: string | null; avg_total_margin: string | null };

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-05 CMS ownership & control network, state-neutral (KY + FL).
 * No individual owner name or personal address is present anywhere in this
 * payload — organization-level owner facts only.
 */
export const OWNERSHIP_NETWORK = ${JSON.stringify(payload, null, 2)};
`;
}

const CHAIN_CAP = 20;

/**
 * Business Action: ExportOwnershipNetworkForUi
 * Exports per-state ownership-chain rollups and churn metrics. Every
 * ownership signal is labeled a review candidate, never an adverse finding.
 */
export class ExportOwnershipNetworkForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.ownershipNetworkExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_ownership_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const chains = await this.client.query<ChainRow>(
        `SELECT state_code, owner_organization_name, facility_count::text, total_beds::text, avg_total_margin::text
         FROM bw_dso.dso_ownership_chain_rollup WHERE load_class='REAL' ORDER BY facility_count DESC`,
      );

      const check = new CheckOwnershipNetworkNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        byState[state] = {
          state,
          organizationLevelOnly: 'No individual owner name or personal address is present anywhere in this payload — organization-level owner facts only, per the person-level gate.',
          coverageNote: 'Scoped to Hospital and SNF facilities already loaded in OFR-04, matched to CMS ownership records by exact normalized facility name. Hospice and Home Health Agency ownership is out of scope for this package (documented boundary, not a gap).',
          metrics: stateMetrics,
          ownershipChains: {
            note: 'Owner organizations controlling more than one loaded facility — a review candidate list for common-ownership analysis, never itself a finding of anticompetitive conduct, quality failure, or program integrity violation.',
            chains: chains.rows.filter((c) => c.state_code === state).slice(0, CHAIN_CAP).map((c) => ({
              ownerOrganizationName: c.owner_organization_name,
              facilityCount: Number(c.facility_count),
              totalBeds: c.total_beds == null ? null : Number(c.total_beds),
              avgTotalMargin: c.avg_total_margin == null ? null : Number(c.avg_total_margin),
            })),
          },
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/ownership-network/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        scope: 'CMS Hospital + SNF "All Owners" PUFs, matched to the OFR-04 KY+FL facility universe by exact normalized name',
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
