import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import {
  CountPublicHydrationPsaByFromSysId,
  CountRecordsInPsaObject,
  IsPublicHydrationPsaObject,
  PsaObjectBelongsToFromSysId,
} from '../atoms/CountPsaSourceRecords.js';
import {
  ObservePublisherSourceScale,
  type PublisherSourceScale,
  type SourceScaleBatch,
} from '../atoms/ObservePublisherSourceRecords.js';
import { config, REPO_ROOT } from '../config.js';
import { SOURCE_SYSTEMS } from '../catalog/seedCatalog.js';
import { readFixtureJson } from './SeedWarehouseCatalog.js';

const ALP = path.join(REPO_ROOT, 'wireframe V1', 'app', 'src', 'data', 'alp');
const DOCS_PLANNING = path.join(REPO_ROOT, 'docs', 'planning');

type AvailablePack = {
  note?: string;
  sources: Record<
    string,
    {
      publisher?: string;
      grain?: string;
      cadence?: string;
      availableDepth?: string;
      publicUris?: string[];
      seriesKind?: string;
      /** Publisher-side size (not PSA land). */
      sourceRecordCount?: number | null;
      sourceRecordUnit?: string;
      sourceRecordNote?: string;
      sourceCountUri?: string;
      sourceCountUris?: string[];
      sourceCountApiUrl?: string;
      sourceCountApiField?: string;
      sourcePeriodColumn?: string;
      sourcePeriodBatchKind?: string;
      sourcePeriodBatchLabel?: string;
      sourceScaleBatches?: SourceScaleBatch[];
      sourceScaleRecordHint?: string;
      definitionBreakNotes?: string[];
      psaBind?: {
        mode?: string;
        criteria?: string[];
        why?: string;
      };
      archiveProbe?: Array<{
        periodId: string;
        uri: string;
        httpStatus: number;
        parseStatus: string;
      }>;
    }
  >;
  measureConsumers?: Record<
    string,
    { rooms?: string[]; tiles?: string[]; findings?: string[] }
  >;
};

type Pack = {
  asOfDate: string;
  landingMeasures: Array<{
    measureId: string;
    asOfDate: string;
    fromSysId: string;
    periodId?: string;
    numericValue: number | null;
    displayValue: string;
  }>;
  gaps: Array<{
    gapId: string;
    title: string;
    need: string;
    rooms: string[];
    findingIds: string[];
    paidFollowOn: string;
  }>;
};

function writeJs(exportName: string, payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * Data Spectrum trust inventory (LoadClass=REAL gate).
 */
export const ${exportName} = ${JSON.stringify(payload, null, 2)};
`;
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))].sort();
}

/**
 * Business Action: ExportDataSpectrumForUi
 * Machine inventory of Available vs Loaded vs Used vs Gaps/Inconsistencies per FromSysID + Explicit Gaps.
 */
export class ExportDataSpectrumForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = path.join(ALP, 'dataSpectrum.js');
  MarkdownPath = path.join(DOCS_PLANNING, 'data-spectrum-latest.md');
  RowCount = 0;

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const available = await readFixtureJson<AvailablePack>('dataSpectrumAvailable.json');
      const pack = await readFixtureJson<Pack>('realPublicHydrationPack.json');

      // Resultant = current logical cube aggregates (dedupe gate re-loads of same measure×as-of).
      const landing = await this.client.query<{
        measure_id: string;
        as_of_date: string;
        from_sys_id: string;
        numeric_value: string | null;
        display_value: string;
        provenance_json: { periodId?: string; periodYm?: string } | null;
      }>(
        `SELECT DISTINCT ON (c.from_sys_id, c.measure_id, c.as_of_date)
           c.measure_id,
           c.as_of_date::text,
           c.from_sys_id,
           c.numeric_value::text,
           c.display_value,
           c.provenance_json
         FROM bw_cube.cube_exec_landing c
         JOIN bw_ctl.load_history h ON h.load_history_id = c.load_history_id
         WHERE c.load_class = 'REAL'
         ORDER BY c.from_sys_id, c.measure_id, c.as_of_date,
           COALESCE(h.completed_at, h.started_at) DESC`,
      );

      const bySys = new Map<string, typeof landing.rows>();
      for (const row of landing.rows) {
        const list = bySys.get(row.from_sys_id) || [];
        list.push(row);
        bySys.set(row.from_sys_id, list);
      }

      // Resultant cubes = Evidence Room cubes (latest land per row_id), with:
      // - per-source rows in each cube, and
      // - full fact-table size for that cube (all REAL sources).
      const roomRows = await this.client.query<{
        from_sys_id: string;
        room_id: string;
        row_id: string;
      }>(
        `SELECT DISTINCT ON (r.from_sys_id, r.room_id, r.row_id)
           r.from_sys_id, r.room_id, r.row_id
         FROM bw_cube.cube_room_row r
         JOIN bw_ctl.load_history h ON h.load_history_id = r.load_history_id
         WHERE r.load_class = 'REAL'
           AND r.row_kind = 'REAL'
           AND r.from_sys_id <> ''
         ORDER BY r.from_sys_id, r.room_id, r.row_id,
           COALESCE(h.completed_at, h.started_at) DESC`,
      );
      const roomBySys = new Map<string, Map<string, number>>();
      const factRowsByCube = new Map<string, number>();
      for (const row of roomRows.rows) {
        const rooms = roomBySys.get(row.from_sys_id) || new Map<string, number>();
        rooms.set(row.room_id, (rooms.get(row.room_id) || 0) + 1);
        roomBySys.set(row.from_sys_id, rooms);
        factRowsByCube.set(row.room_id, (factRowsByCube.get(row.room_id) || 0) + 1);
      }

      // Loaded = current PSA land size:
      // - dedicated FromSysID objects (latest land), plus
      // - per-FromSysID slices inside the latest PUBLIC_HYDRATION shared pack.
      const psaObjects = await this.client.query<{ from_sys_id: string; object_key: string }>(
        `SELECT DISTINCT ON (from_sys_id)
           from_sys_id, object_key
         FROM bw_psa_meta.object_index
         WHERE load_class = 'REAL'
         ORDER BY from_sys_id, landed_at DESC`,
      );
      const psaLoadedBySys = new Map<string, number>();
      for (const row of psaObjects.rows) {
        if (IsPublicHydrationPsaObject(row.object_key)) continue;
        if (!PsaObjectBelongsToFromSysId(row.object_key, row.from_sys_id)) continue;
        const counted = await CountRecordsInPsaObject(row.object_key);
        if (!counted) continue;
        psaLoadedBySys.set(
          row.from_sys_id,
          (psaLoadedBySys.get(row.from_sys_id) || 0) + counted.recordCount,
        );
      }

      const hydrationLatest = await this.client.query<{ object_key: string }>(
        `SELECT object_key
         FROM bw_psa_meta.object_index
         WHERE load_class = 'REAL'
           AND object_key ILIKE '%PUBLIC_HYDRATION%'
         ORDER BY landed_at DESC
         LIMIT 1`,
      );
      if (hydrationLatest.rows[0]?.object_key) {
        const byHydration = await CountPublicHydrationPsaByFromSysId(
          hydrationLatest.rows[0].object_key,
        );
        for (const [fromSysId, n] of byHydration) {
          psaLoadedBySys.set(fromSysId, (psaLoadedBySys.get(fromSysId) || 0) + n);
        }
      }

      // Publisher-side Source scale (batches + records; research + optional live CSV fetch) — NOT PSA size.
      const publisherBySys = new Map<string, PublisherSourceScale | null>();
      for (const s of SOURCE_SYSTEMS.filter((x) => x.from_sys_id !== 'TEST_FIXTURE_PACK')) {
        const meta = available.sources[s.from_sys_id] || {};
        publisherBySys.set(s.from_sys_id, await ObservePublisherSourceScale(meta));
      }

      const gapsQ = await this.client.query<{
        gap_id: string;
        title: string;
        need: string;
        rooms: string[];
        finding_ids: string[];
        paid_follow_on: string;
      }>(`SELECT gap_id, title, need, rooms, finding_ids, paid_follow_on FROM bw_ctl.gap_object ORDER BY gap_id`);

      const sourceRows = [];
      for (const s of SOURCE_SYSTEMS.filter((x) => x.from_sys_id !== 'TEST_FIXTURE_PACK')) {
        const meta = available.sources[s.from_sys_id] || {};
        const loaded = bySys.get(s.from_sys_id) || [];
        const measureIds = uniqueSorted(loaded.map((r) => r.measure_id));
        const asOfDates = uniqueSorted(loaded.map((r) => r.as_of_date));
        const periodIds = uniqueSorted(
          loaded.map((r) => r.provenance_json?.periodId || r.provenance_json?.periodYm || '').filter(Boolean),
        );
        const landingRowCount = loaded.length;
        const roomMap = roomBySys.get(s.from_sys_id) || new Map<string, number>();
        const resultantCubes = [...roomMap.entries()]
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([roomId, rowCount]) => ({
            cubeId: roomId,
            label: roomId,
            /** REAL rows in this cube attributed to this FromSysID. */
            rowCount,
            /** REAL rows in the cube fact table (all sources). */
            factRowCount: factRowsByCube.get(roomId) || rowCount,
          }));
        const resultantCubeCount = resultantCubes.length;
        const resultantRows = resultantCubes.reduce((n, c) => n + c.rowCount, 0);
        const psaLoadedRows = psaLoadedBySys.get(s.from_sys_id) || 0;
        const publisher = publisherBySys.get(s.from_sys_id) || null;
        const sourceScale: PublisherSourceScale | null = publisher;
        const sourceRecordUnit = publisher?.recordUnit || meta.sourceRecordUnit || 'records';
        const sourceRecordNote =
          publisher?.note ||
          meta.sourceRecordNote ||
          'Publisher-side scale not yet observed for this SoT.';
        const sourceRecordCount = sourceScale?.recordCount ?? null;
        const sourceRecordScope = sourceScale?.scope || publisher?.scope || 'unknown';
        const consumers = measureIds.flatMap((mid) => {
          const c = available.measureConsumers?.[mid];
          return c
            ? [
                ...(c.rooms || []).map((r) => `room:${r}`),
                ...(c.tiles || []).map((t) => `tile:${t}`),
                ...(c.findings || []).map((f) => `finding:${f}`),
              ]
            : [];
        });

        const inconsistencies: string[] = [...(meta.definitionBreakNotes || [])];
        if (meta.archiveProbe?.length) {
          const notFound = meta.archiveProbe.filter((probe) => probe.parseStatus === 'NOT_FOUND');
          const otherBad = meta.archiveProbe.filter(
            (probe) => probe.parseStatus !== 'NOT_FOUND' && probe.parseStatus !== 'LOADED',
          );
          if (notFound.length > 3) {
            const sample = notFound
              .slice(0, 3)
              .map((p) => p.periodId)
              .join(', ');
            inconsistencies.push(
              `Archive day-sweep: ${notFound.length} months HTTP 404 / not on public path (e.g. ${sample}, …). See Source Timeline probes.`,
            );
          } else {
            for (const probe of notFound) {
              inconsistencies.push(
                `Archive PDF ${probe.periodId} HTTP ${probe.httpStatus} — not loaded (${probe.uri})`,
              );
            }
          }
          for (const probe of otherBad) {
            inconsistencies.push(
              `Archive PDF ${probe.periodId} parseStatus=${probe.parseStatus} (${probe.uri})`,
            );
          }
        }
        if (s.from_sys_id === 'CMS_MEDICAID_PHARMACY' && measureIds.includes('M-017') && asOfDates.length < 2) {
          inconsistencies.push(
            'CMS Spending by Drug publishes ~5 national year columns; KY curated pack currently binds one annual aggregate — not a synthetic multi-year KY stretch.',
          );
        }
        if (s.from_sys_id === 'CMS_MEDICAID_SCORECARD') {
          const coreSetYears = uniqueSorted(
            pack.landingMeasures
              .filter((m) => m.fromSysId === 'CMS_MEDICAID_SCORECARD')
              .map((m) => {
                const row = m as {
                  coreSetYear?: number;
                  periodId?: string;
                  asOfDate: string;
                };
                if (row.coreSetYear != null) return String(row.coreSetYear);
                if (row.periodId?.startsWith('ffy')) return row.periodId.slice(3);
                return row.asOfDate.slice(0, 4);
              }),
          );
          if (!coreSetYears.includes('2024')) {
            inconsistencies.push(
              'Core Set FFY 2024 CSV not loaded — resolve alternate URI via scripts/resolve-core-set-csv.mjs before recording unpublished.',
            );
          }
          const wcvCoreYears = pack.landingMeasures
            .filter((m) => m.measureId === 'M-010')
            .map((m) => {
              const row = m as { coreSetYear?: number; periodId?: string; asOfDate: string };
              if (row.coreSetYear != null) return String(row.coreSetYear);
              if (row.periodId?.startsWith('ffy')) return row.periodId.slice(3);
              return row.asOfDate.slice(0, 4);
            });
          if (!wcvCoreYears.includes('2020')) {
            inconsistencies.push('WCV-CH definition/vintage gap: abbreviation absent from 2020 Core Set CSV.');
          }
        }

        const blockReason =
          'block_reason' in s ? String((s as { block_reason?: string }).block_reason || '') : '';
        const unblockNeed =
          'unblock_need' in s ? String((s as { unblock_need?: string }).unblock_need || '') : '';

        let disposition: 'LOADED' | 'CATALOGUED' | 'BLOCKED' = 'CATALOGUED';
        if (s.tos_grade === 'RESTRICTED' || s.tos_grade === 'OUT_OF_POC' || blockReason) {
          disposition = 'BLOCKED';
        } else if (
          loaded.length > 0 ||
          s.from_sys_id === 'CMS_DATA_MEDICAID_ENR' ||
          s.from_sys_id === 'KY_DMS_MCO_CONTRACTS'
        ) {
          disposition = 'LOADED';
        }

        let nextAction = s.paid_follow_on_todo || '';
        if (disposition === 'CATALOGUED' && !nextAction) {
          nextAction = 'Director-authorize curated extract or Data Request bind';
        }
        if (disposition === 'BLOCKED') {
          nextAction = unblockNeed || nextAction || 'Obtain license/DUA then Director-authorize REAL load';
        }

        sourceRows.push({
          kind: 'source' as const,
          fromSysId: s.from_sys_id,
          publisher: s.publisher,
          tosGrade: s.tos_grade,
          disposition,
          provides: {
            publisher: meta.publisher || s.publisher,
            grain: meta.grain || '',
            cadence: meta.cadence || '',
            publicUris: meta.publicUris || [s.base_uri],
            tosGrade: s.tos_grade,
            seriesKind: meta.seriesKind || 'unknown',
          },
          availableDepth: meta.availableDepth || s.attribution_notes,
          loadedDepth: {
            measureIds,
            asOfDates,
            periodIds,
            /** @deprecated use loadedRowCount — kept for older UI readers */
            rowCount: psaLoadedRows,
            sourceRecordCount,
            sourceRecordUnit,
            sourceRecordScope,
            sourceRecordNote,
            sourceScale: sourceScale || {
              label: '—',
              batches: [],
              recordCount: null,
              recordUnit: sourceRecordUnit,
              note: sourceRecordNote,
              scope: 'research' as const,
            }, // bare dash only when nothing landed and publisher scale unknown
            loadedRowCount: psaLoadedRows,
            landingRowCount,
            resultantCubeCount,
            resultantCubes,
            /** Total REAL Evidence Room rows across cubes (sum of resultantCubes.rowCount). */
            resultantRowCount: resultantRows,
            /** Explicit PSA bind filters (criteria + why) from inventory research. */
            psaBind: meta.psaBind
              ? {
                  mode: String(meta.psaBind.mode || 'filtered'),
                  criteria: Array.isArray(meta.psaBind.criteria)
                    ? meta.psaBind.criteria.map(String)
                    : [],
                  why: String(meta.psaBind.why || ''),
                }
              : undefined,
            earliestAsOf: asOfDates[0] || null,
            latestAsOf: asOfDates[asOfDates.length - 1] || null,
          },
          howUsed: {
            measureIds,
            consumers: uniqueSorted(consumers),
          },
          inconsistencies,
          nextAction,
          blockReason: blockReason || undefined,
        });
      }

      // Ensure enrollment shows loaded even when cube rows exist under CMS_DATA_MEDICAID_ENR
      for (const row of sourceRows) {
        if (row.fromSysId === 'CMS_DATA_MEDICAID_ENR' || row.fromSysId === 'KY_DMS_MCO_CONTRACTS') {
          row.disposition = 'LOADED';
        }
      }

      const gapRows = gapsQ.rows.map((g) => ({
        kind: 'gap' as const,
        fromSysId: g.gap_id,
        publisher: 'Explicit Gap',
        tosGrade: 'GAP',
        disposition: 'GAP' as const,
        provides: {
          publisher: 'Not publicly fillable',
          grain: 'n/a',
          cadence: 'n/a',
          publicUris: [],
          tosGrade: 'GAP',
          seriesKind: 'none',
        },
        availableDepth: 'No continuous public series — requires authorized feed / DUA / license.',
        loadedDepth: {
          measureIds: [],
          asOfDates: [],
          periodIds: [],
          rowCount: 0,
          sourceRecordCount: null,
          sourceRecordUnit: 'records',
          sourceRecordScope: 'unknown',
          sourceRecordNote: 'Explicit Gap — no publisher SoT to count.',
          sourceScale: {
            label: '—',
            batches: [],
            recordCount: null,
            recordUnit: 'records',
            note: 'Explicit Gap — no publisher SoT to count.',
            scope: 'research' as const,
          },
          loadedRowCount: 0,
          landingRowCount: 0,
          resultantCubeCount: 0,
          resultantCubes: [] as Array<{
            cubeId: string;
            label: string;
            rowCount: number;
            factRowCount: number;
          }>,
          resultantRowCount: 0,
          earliestAsOf: null,
          latestAsOf: null,
        },
        howUsed: {
          measureIds: [],
          consumers: uniqueSorted([
            ...g.rooms.map((r) => `room:${r}`),
            ...g.finding_ids.map((f) => `finding:${f}`),
          ]),
        },
        inconsistencies: [`Gap remains unlabeled as history: ${g.title}`],
        nextAction: g.paid_follow_on,
        title: g.title,
        need: g.need,
      }));

      const rows = [...sourceRows, ...gapRows];
      this.RowCount = rows.length;

      const loadedSources = sourceRows.filter((r) => r.disposition === 'LOADED').length;
      const cataloguedSources = sourceRows.filter((r) => r.disposition === 'CATALOGUED').length;
      const blockedSources = sourceRows.filter((r) => r.disposition === 'BLOCKED').length;
      const allAsOf = uniqueSorted(landing.rows.map((r) => r.as_of_date));

      const payload = {
        schema: 'decisionpro/data-spectrum/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        product: 'DecisionPro',
        note:
          'Machine-exported Data Spectrum. Source scale = publisher SoT batching + record totals (not PSA land). Loaded = records landed into PSA. Resultant = Evidence Room cubes this source feeds, with REAL row counts per cube.',
        availableNote: available.note || '',
        summary: {
          sourcesLoaded: loadedSources,
          sourcesCatalogued: cataloguedSources,
          sourcesBlocked: blockedSources,
          explicitGaps: gapRows.length,
          earliestRealAsOf: allAsOf[0] || null,
          latestRealAsOf: allAsOf[allAsOf.length - 1] || null,
          landingRowCount: landing.rows.length, // distinct measure×as-of (current), not historical re-load copies
          gateTimestamp: new Date().toISOString(),
        },
        rows,
      };

      await fs.mkdir(ALP, { recursive: true });
      await fs.writeFile(this.ExportPath, writeJs('DATA_SPECTRUM', payload), 'utf8');

      const md = renderMarkdown(payload);
      await fs.mkdir(DOCS_PLANNING, { recursive: true });
      await fs.writeFile(this.MarkdownPath, md, 'utf8');

      const jsonSide = path.join(config.psaRoot, '..', 'exports', 'data-spectrum.json');
      await fs.mkdir(path.dirname(jsonSide), { recursive: true });
      await fs.writeFile(jsonSide, JSON.stringify(payload, null, 2), 'utf8');

      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }
}

function renderMarkdown(payload: {
  generatedAt: string;
  summary: Record<string, unknown>;
  rows: Array<Record<string, unknown>>;
}): string {
  const s = payload.summary;
  const lines = [
    '# Data Spectrum (latest gate export)',
    '',
    `Generated: ${payload.generatedAt}`,
    '',
    '## Summary',
    '',
    `- Sources loaded: ${s.sourcesLoaded}`,
    `- Sources catalogued: ${s.sourcesCatalogued}`,
    `- Sources blocked: ${s.sourcesBlocked}`,
    `- Explicit gaps: ${s.explicitGaps}`,
    `- REAL as-of window: ${s.earliestRealAsOf || '—'} → ${s.latestRealAsOf || '—'}`,
    `- Landing cube rows: ${s.landingRowCount}`,
    '',
    '## Inventory',
    '',
  ];
  for (const row of payload.rows) {
    const id = String(row.fromSysId);
    const disp = String(row.disposition);
    const available = String(row.availableDepth || '');
    const loaded = row.loadedDepth as {
      rowCount?: number;
      sourceRecordCount?: number | null;
      sourceRecordUnit?: string;
      sourceRecordNote?: string;
      sourceScale?: { label?: string; note?: string };
      loadedRowCount?: number;
      landingRowCount?: number;
      resultantCubeCount?: number;
      resultantCubes?: Array<{
        cubeId: string;
        label: string;
        rowCount: number;
        factRowCount?: number;
      }>;
      resultantRowCount?: number;
      earliestAsOf?: string;
      latestAsOf?: string;
    };
    const inconsist = (row.inconsistencies as string[]) || [];
    const scaleLabel =
      loaded.sourceScale?.label ||
      (loaded.sourceRecordCount == null
        ? '—'
        : `${Number(loaded.sourceRecordCount).toLocaleString()} ${loaded.sourceRecordUnit || 'records'}`);
    const cubeBits = (loaded.resultantCubes || [])
      .map((c) => {
        const fact = c.factRowCount ?? c.rowCount;
        return `${c.label}: ${c.rowCount} src / ${fact} fact`;
      })
      .join('; ');
    lines.push(`### ${id} — ${disp}`);
    lines.push('');
    lines.push(`- **Available:** ${available}`);
    lines.push(
      `- **Source scale:** ${scaleLabel}${
        loaded.sourceRecordNote || loaded.sourceScale?.note
          ? ` (${loaded.sourceRecordNote || loaded.sourceScale?.note})`
          : ''
      }`,
    );
    lines.push(
      `- **Loaded (PSA):** ${loaded.loadedRowCount ?? loaded.rowCount ?? 0}${
        loaded.earliestAsOf ? ` (${loaded.earliestAsOf} → ${loaded.latestAsOf})` : ''
      }`,
    );
    lines.push(
      `- **Resultant (cubes):** ${loaded.resultantCubeCount ?? 0} cubes · ${
        loaded.resultantRowCount ?? 0
      } rows${cubeBits ? ` (${cubeBits})` : ''}; landing binds: ${loaded.landingRowCount ?? 0}`,
    );
    if (inconsist.length) {
      lines.push(`- **Inconsistencies:** ${inconsist.join('; ')}`);
    }
    lines.push(`- **Next:** ${row.nextAction || '—'}`);
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}
