import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';

type LandingRow = {
  measure_id: string;
  display_value: string;
  numeric_value: string | null;
  unit: string;
  as_of_date: string;
  from_sys_id: string;
  load_history_id: string;
  provenance_json: unknown;
  name: string;
  definition: string;
};

function enrichProvenance(
  provenanceRaw: unknown,
  fromSysId: string,
  pageMap: Map<string, string>,
) {
  const provenance =
    provenanceRaw && typeof provenanceRaw === 'object'
      ? { ...(provenanceRaw as Record<string, unknown>) }
      : {};
  const sourceUri = String(provenance.sourceUri || '');
  const mappedPage = pageMap.get(fromSysId) || '';
  const existingPage = String(provenance.sourcePageUri || '');
  if (mappedPage && mappedPage !== sourceUri && (!existingPage || existingPage === sourceUri)) {
    provenance.sourcePageUri = mappedPage;
  } else if (!existingPage) {
    provenance.sourcePageUri = mappedPage || sourceUri;
  }
  return provenance;
}

function toMeasure(row: LandingRow, pageMap: Map<string, string>) {
  return {
    measureId: row.measure_id,
    name: row.name,
    definition: row.definition,
    displayValue: row.display_value,
    numericValue: row.numeric_value == null ? null : Number(row.numeric_value),
    unit: row.unit,
    asOfDate: row.as_of_date,
    fromSysId: row.from_sys_id,
    loadHistoryId: row.load_history_id,
    provenance: enrichProvenance(row.provenance_json, row.from_sys_id, pageMap),
  };
}

/**
 * Business Action: ExportAccurateLandingForUi
 * Writes REAL cube snapshot for wireframe accurate path (static-hostable).
 * `measures` = latest row per measure; `measureSeries` = all as_of_date rows.
 */
export class ExportAccurateLandingForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.exportPath;
  MeasureCount = 0;

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const r = await this.client.query<LandingRow>(
        `SELECT
           c.measure_id, c.display_value, c.numeric_value::text, c.unit,
           c.as_of_date::text, c.from_sys_id, c.load_history_id, c.provenance_json,
           m.name, m.definition
         FROM bw_cube.cube_exec_landing c
         JOIN bw_ctl.measure m ON m.measure_id = c.measure_id
         WHERE c.load_class = 'REAL'
         ORDER BY c.measure_id, c.as_of_date ASC, c.load_history_id DESC`,
      );

      const pageBySys = await this.client.query<{ from_sys_id: string; base_uri: string }>(
        `SELECT from_sys_id, base_uri FROM bw_ctl.source_system`,
      );
      const pageMap = new Map(pageBySys.rows.map((s) => [s.from_sys_id, s.base_uri]));

      const measureSeries = r.rows.map((row) => toMeasure(row, pageMap));
      const latestById = new Map<string, (typeof measureSeries)[number]>();
      for (const m of measureSeries) latestById.set(m.measureId, m);
      const measures = [...latestById.values()];
      this.MeasureCount = measures.length;

      const payload = {
        schema: 'decisionpro/accurate-landing/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        product: 'DecisionPro',
        note: 'Values from XenoDroid BW REAL loads — not synthetic fixtures. measureSeries holds multi-period rows.',
        measures,
        measureSeries,
      };

      const js = `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * Accurate public-data landing snapshot (LoadClass=REAL).
 */
export const ACCURATE_LANDING = ${JSON.stringify(payload, null, 2)};
`;
      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, js, 'utf8');

      const jsonSide = path.join(config.psaRoot, '..', 'exports', 'accurate-landing.json');
      await fs.mkdir(path.dirname(jsonSide), { recursive: true });
      await fs.writeFile(jsonSide, JSON.stringify(payload, null, 2), 'utf8');

      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }
}
