import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckNonprofitFinancialsNumbers } from './CheckNonprofitFinancialsNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type FilingRow = {
  ein: string; tax_period: string; extract_vintage: string; org_name: string; state_code: string;
  total_revenue: string | null; total_expenses: string | null; total_contributions_grants: string | null;
  unrestricted_net_assets_end: string | null; admin_category_expense: string | null;
};

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-03 IRS Form 990 organization-level financial resilience, state-neutral (KY + FL).
 * Organization-level only — no officer, donor, or person-level fields.
 */
export const NONPROFIT_FINANCIALS = ${JSON.stringify(payload, null, 2)};
`;
}

const REVIEW_CANDIDATE_CAP = 15;

/**
 * Business Action: ExportNonprofitFinancialsForUi
 * Exports per-state resilience-ratio summary metrics plus a bounded
 * lowest-liquidity review-candidate list. Every ratio is labeled as a
 * review signal, never a finding — per the no-adverse-conclusion gate.
 */
export class ExportNonprofitFinancialsForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.nonprofitFinancialsExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_nonprofit_resilience_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const filings = await this.client.query<FilingRow>(
        `SELECT ein, tax_period, extract_vintage, org_name, state_code,
           total_revenue::text, total_expenses::text, total_contributions_grants::text,
           unrestricted_net_assets_end::text, admin_category_expense::text
         FROM bw_dso.dso_nonprofit_filing WHERE load_class='REAL'`,
      );

      // Relevance gate (2026-09-02): EINs that reach the depot through another
      // governed source — an exact crosswalk assertion (UEI↔EIN, EIN↔NPI,
      // EIN↔CCN) or an identity-resolved sub-award edge. Only these
      // organizations are Medicaid-adjacent by evidence; the unfiltered
      // lowest-liquidity list is dominated by dormant filers.
      const crosswalkEins = await this.client.query<{ state_code: string; ein: string; link: string }>(
        `SELECT state_code,
           CASE WHEN left_identifier_type='EIN' THEN left_identifier_value ELSE right_identifier_value END AS ein,
           CASE WHEN left_identifier_type='EIN' THEN right_identifier_type ELSE left_identifier_type END AS link
         FROM bw_ctl.organization_crosswalk_exact
         WHERE load_class='REAL' AND (left_identifier_type='EIN' OR right_identifier_type='EIN')`,
      );
      const edgeEins = await this.client.query<{ state_code: string; ein: string; amount: string | null; assistance_listing: string }>(
        `SELECT state_code, recipient_ein AS ein, amount::text, assistance_listing
         FROM bw_dso.dso_funding_edge WHERE load_class='REAL' AND recipient_ein IS NOT NULL`,
      );

      const check = new CheckNonprofitFinancialsNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        const stateFilings = filings.rows.filter((f) => f.state_code === state);
        const withLiquidity = stateFilings
          .map((f) => {
            const netAssets = f.unrestricted_net_assets_end == null ? null : Number(f.unrestricted_net_assets_end);
            const expenses = f.total_expenses == null ? null : Number(f.total_expenses);
            const months = netAssets != null && expenses ? netAssets / (expenses / 12) : null;
            return { ...f, liquidityMonths: months };
          })
          .filter((f) => f.liquidityMonths != null)
          .sort((a, b) => (a.liquidityMonths! - b.liquidityMonths!));

        const depotLinks = new Map<string, Set<string>>();
        for (const row of crosswalkEins.rows.filter((r) => r.state_code === state)) {
          const links = depotLinks.get(row.ein) || new Set<string>();
          links.add(`EIN↔${row.link} (exact crosswalk)`);
          depotLinks.set(row.ein, links);
        }
        const edgeAmountByEin = new Map<string, { amount: number; listings: Set<string> }>();
        for (const row of edgeEins.rows.filter((r) => r.state_code === state)) {
          const links = depotLinks.get(row.ein) || new Set<string>();
          links.add('sub-award recipient (identity-resolved edge)');
          depotLinks.set(row.ein, links);
          const current = edgeAmountByEin.get(row.ein) || { amount: 0, listings: new Set<string>() };
          current.amount += Number(row.amount || 0);
          current.listings.add(row.assistance_listing);
          edgeAmountByEin.set(row.ein, current);
        }
        const latestByEin = new Map<string, typeof withLiquidity[number]>();
        for (const f of withLiquidity) {
          const current = latestByEin.get(f.ein);
          if (!current || f.tax_period > current.tax_period) latestByEin.set(f.ein, f);
        }
        const depotLinked = [...latestByEin.values()]
          .filter((f) => depotLinks.has(f.ein))
          .map((f) => {
            const periods = withLiquidity.filter((row) => row.ein === f.ein).sort((a, b) => b.tax_period.localeCompare(a.tax_period));
            const edge = edgeAmountByEin.get(f.ein);
            return {
              ein: f.ein, orgName: f.org_name, taxPeriod: f.tax_period, extractVintage: f.extract_vintage,
              liquidityMonths: f.liquidityMonths == null ? null : Number(f.liquidityMonths.toFixed(1)),
              priorPeriodLiquidityMonths: periods[1]?.liquidityMonths == null ? null : Number(periods[1].liquidityMonths.toFixed(1)),
              lowLiquidityBothPeriods: periods.length >= 2 && periods.slice(0, 2).every((row) => row.liquidityMonths != null && row.liquidityMonths < 3),
              totalRevenue: f.total_revenue == null ? null : Number(f.total_revenue),
              totalExpenses: f.total_expenses == null ? null : Number(f.total_expenses),
              depotLinks: [...(depotLinks.get(f.ein) || [])].sort(),
              subawardAmount: edge ? edge.amount : null,
              subawardListings: edge ? [...edge.listings].sort() : [],
            };
          })
          .sort((a, b) => (a.liquidityMonths ?? 0) - (b.liquidityMonths ?? 0));

        byState[state] = {
          state,
          organizationLevelOnly: 'No officer, donor, or person-level fields are collected or exported. IRS 990 XML e-file officer/compensation detail is explicitly out of OFR scope.',
          governmentGrantDependencyNote: 'The IRS SOI extract does not separately break out government-source grants from total Part VIII Line 1 contributions (individual + foundation + corporate + government). This is a contribution-and-grant revenue dependency ratio, not a government-specific one.',
          programVsAdminNote: 'The extract does not carry the Form 990 Part IX (B)/(C)/(D) program/management/fundraising functional-expense column split. "Admin category share" sums named administrative line items (management/legal/accounting/lobbying/investment-management fees, office expenses) over total functional expenses — a proxy, not the official allocation.',
          metrics: stateMetrics,
          reviewCandidates: {
            note: 'Lowest-liquidity filings this run — a review prompt for financial-resilience follow-up, never a finding of distress, mismanagement, or wrongdoing.',
            lowestLiquidity: withLiquidity.slice(0, REVIEW_CANDIDATE_CAP).map((f) => ({
              ein: f.ein, orgName: f.org_name, taxPeriod: f.tax_period, extractVintage: f.extract_vintage,
              liquidityMonths: f.liquidityMonths == null ? null : Number(f.liquidityMonths.toFixed(1)),
              totalRevenue: f.total_revenue == null ? null : Number(f.total_revenue),
              totalExpenses: f.total_expenses == null ? null : Number(f.total_expenses),
            })),
          },
          depotLinkedCandidates: {
            note: 'Filings for organizations that reach the depot through another governed source (an exact identity crosswalk assertion or an identity-resolved sub-award edge), latest filing period per EIN, lowest liquidity first. This is the relevance-gated resilience list: Medicaid-adjacent by evidence, still a review prompt and never a finding of distress.',
            linkedEinCount: depotLinks.size,
            filingsMatched: depotLinked.length,
            lowLiquidityCount: depotLinked.filter((f) => f.liquidityMonths != null && f.liquidityMonths < 3).length,
            organizations: depotLinked,
          },
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/nonprofit-financials/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        formType: '990',
        vintages: config.irs990ExtractUris.map((v) => v.vintage),
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
