import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config, REPO_ROOT } from '../config.js';
import { readFixtureJson } from './SeedWarehouseCatalog.js';
import { SOURCE_SYSTEMS } from '../catalog/seedCatalog.js';
const ALP = path.join(REPO_ROOT, 'wireframe V1', 'app', 'src', 'data', 'alp');
function writeJs(name: string, exportName: string, payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * Public-REAL hydration cutover (${name}).
 */
export const ${exportName} = ${JSON.stringify(payload, null, 2)};
`;
}
type Pack = {
  asOfDate: string;
  attribution: string;
  legislation: Array<Record<string, unknown>>;
  landingMeasures: Array<{
    measureId: string;
    displayValue: string;
    numericValue: number | null;
    fromSysId: string;
    sourceUri: string;
    asOfDate: string;
    note?: string;
    periodId?: string;
  }>;
  gaps: Array<{
    gapId: string;
    title: string;
    need: string;
    rooms: string[];
    findingIds: string[];
    paidFollowOn: string;
  }>;
};
/**
 * Business Action: ExportHydrationBundles
 * Writes room cubes, findings, sources, gaps for the wireframe cutover.
 */
export class ExportHydrationBundles {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  FilesWritten: string[] = [];
  constructor(private client: pg.PoolClient) {}
  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const pack = await readFixtureJson<Pack>('realPublicHydrationPack.json');
      const roomQ = await this.client.query<{
        row_id: string;
        room_id: string;
        title: string;
        metric_key: string;
        metric_value: string | null;
        display_value: string;
        row_kind: string;
        dimensions_json: Record<string, string>;
        payload_json: Record<string, unknown>;
        from_sys_id: string;
        as_of_date: string | null;
      }>(
        `SELECT DISTINCT ON (row_id)
           row_id, room_id, title, metric_key, metric_value::text, display_value, row_kind,
           dimensions_json, payload_json, from_sys_id, as_of_date::text
         FROM bw_cube.cube_room_row
         WHERE load_class = 'REAL'
         ORDER BY row_id, load_history_id DESC`,
      );
      const rooms: Record<string, unknown[]> = {};
      for (const r of roomQ.rows) {
        if (!rooms[r.room_id]) rooms[r.room_id] = [];
        // Prefer multi-period PI rows injected below over the single stub.
        if (r.row_id === 'cc-enroll-trend') continue;
        const dims = r.dimensions_json || {};
        const payload = r.payload_json || {};
        rooms[r.room_id].push({
          id: r.row_id,
          roomId: r.room_id,
          title: r.title,
          rowKind: r.row_kind,
          metricKey: r.metric_key,
          metricValue: r.metric_value == null ? null : Number(r.metric_value),
          displayValue: r.display_value,
          fromSysId: r.from_sys_id,
          asOfDate: r.as_of_date,
          ...dims,
          ...payload,
        });
      }

      const enrollQ = await this.client.query<{
        measure_id: string;
        display_value: string;
        numeric_value: string | null;
        as_of_date: string;
        provenance_json: { periodYm?: string; periodId?: string };
      }>(
        `SELECT measure_id, display_value, numeric_value::text, as_of_date::text, provenance_json
         FROM bw_cube.cube_exec_landing
         WHERE load_class = 'REAL' AND measure_id IN ('M-001','M-002')
         ORDER BY as_of_date ASC`,
      );
      const enrollByDate = new Map<string, { m001?: (typeof enrollQ.rows)[number]; m002?: (typeof enrollQ.rows)[number] }>();
      for (const row of enrollQ.rows) {
        const bucket = enrollByDate.get(row.as_of_date) || {};
        if (row.measure_id === 'M-001') bucket.m001 = row;
        if (row.measure_id === 'M-002') bucket.m002 = row;
        enrollByDate.set(row.as_of_date, bucket);
      }
      if (!rooms['command-center']) rooms['command-center'] = [];
      for (const [asOf, pair] of enrollByDate) {
        const m001 = pair.m001;
        if (!m001) continue;
        const prov = m001.provenance_json || {};
        const periodYm = prov.periodYm || asOf.replace(/-/g, '').slice(0, 6);
        const period = prov.periodId || `pi${periodYm}`;
        const yoy = pair.m002?.numeric_value == null ? null : Number(pair.m002.numeric_value);
        rooms['command-center'].push({
          id: `cc-enroll-${period}`,
          roomId: 'command-center',
          title: 'KY Medicaid & CHIP enrollment (CMS PI)',
          rowKind: 'REAL',
          metricKey: 'count',
          metricValue: m001.numeric_value == null ? null : Number(m001.numeric_value),
          displayValue: `${m001.display_value} persons`,
          fromSysId: 'CMS_DATA_MEDICAID_ENR',
          asOfDate: asOf,
          population: 'all',
          region: 'statewide',
          period,
          attention: 'watch',
          freshness: 'near',
          measureId: 'M-001',
          rate: m001.numeric_value == null ? null : Number(m001.numeric_value),
          trendPts: yoy,
          peerRate: null,
        });
      }

      const roomPayload = {
        schema: 'decisionpro/room-cubes-real/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        note: 'Evidence Room rows — REAL public values or explicit GAP (no synthetic magnitudes)',
        rooms,
      };
      await fs.mkdir(ALP, { recursive: true });
      await fs.writeFile(path.join(ALP, 'roomCubes.real.js'), writeJs('room cubes', 'ROOM_CUBES_REAL', roomPayload), 'utf8');
      this.FilesWritten.push('roomCubes.real.js');
      const gapsQ = await this.client.query<{
        gap_id: string;
        title: string;
        need: string;
        rooms: string[];
        finding_ids: string[];
        paid_follow_on: string;
      }>(`SELECT gap_id, title, need, rooms, finding_ids, paid_follow_on FROM bw_ctl.gap_object ORDER BY gap_id`);
      const gapPayload = {
        schema: 'decisionpro/gap-objects/v1',
        generatedAt: new Date().toISOString(),
        gaps: gapsQ.rows.map((g) => ({
          gapId: g.gap_id,
          title: g.title,
          need: g.need,
          rooms: g.rooms,
          findingIds: g.finding_ids,
          paidFollowOn: g.paid_follow_on,
        })),
      };
      await fs.writeFile(path.join(ALP, 'gapObjects.js'), writeJs('gaps', 'GAP_OBJECTS', gapPayload), 'utf8');
      this.FilesWritten.push('gapObjects.js');
      const landing = Object.fromEntries(pack.landingMeasures.map((m) => [m.measureId, m]));
      const findings = [
        {
          id: 'f-pharmacy',
          focusId: 'budget',
          title: 'Pharmacy expenditure (federal published KY slice)',
          magnitude: landing['M-017'] ? `$${landing['M-017'].displayValue}M` : 'Unavailable',
          magnitudeValue: 0.75,
          budgetRelief: 0.25,
          careResults: 0.35,
          freshness: 'Near current',
          confidence: 0.7,
          constituencyRelevance: 'High',
          disposition: 'REAL',
          measureId: 'M-017',
          sourceIncentiveNote: landing['M-017']?.note || '',
          primarySourceKeys: ['medicaidPharmacy', 'medicaidData', 'kyDms'],
        },
        {
          id: 'f-inpatient-disabled',
          focusId: 'budget',
          title: 'Inpatient days — disabled population',
          magnitude: 'Gap — needs encounters',
          magnitudeValue: 0,
          budgetRelief: 0.3,
          careResults: 0.4,
          freshness: 'Provisional',
          confidence: 0.2,
          constituencyRelevance: 'High',
          disposition: 'GAP',
          gapId: 'GAP-CLAIMS-COST-DRIVERS',
          sourceIncentiveNote: 'No public claim-grain SoT',
          primarySourceKeys: ['kyDms', 'medicaidData'],
        },
        {
          id: 'f-postpartum',
          focusId: 'care',
          title: 'Maternal / postpartum published indicator',
          magnitude: landing['M-012'] ? `${landing['M-012'].displayValue}%` : 'Unavailable',
          magnitudeValue: 0.65,
          budgetRelief: 0.55,
          careResults: 0.78,
          freshness: 'Lagged',
          confidence: 0.72,
          constituencyRelevance: 'Very high',
          disposition: 'REAL',
          measureId: 'M-012',
          sourceIncentiveNote: landing['M-012']?.note || '',
          primarySourceKeys: ['cmsMaternalQuality', 'medicaidScorecard', 'kyDms'],
        },
        {
          id: 'f-diabetes',
          focusId: 'care',
          title: 'Adult Core Set / Scorecard performance (KY)',
          magnitude: landing['M-011'] ? `${landing['M-011'].displayValue}%` : 'Unavailable',
          magnitudeValue: 0.55,
          budgetRelief: 0.5,
          careResults: 0.62,
          freshness: 'Lagged',
          confidence: 0.7,
          constituencyRelevance: 'High',
          disposition: 'REAL',
          measureId: 'M-011',
          sourceIncentiveNote: landing['M-011']?.note || '',
          primarySourceKeys: ['medicaidScorecard', 'cmsDataSearch', 'kyDms'],
        },
        {
          id: 'f-avoidable-ed',
          focusId: 'access',
          title: 'Potentially avoidable ED visits',
          magnitude: 'Gap — HCUP/encounters',
          magnitudeValue: 0,
          budgetRelief: 0.4,
          careResults: 0.55,
          freshness: 'Recent',
          confidence: 0.15,
          constituencyRelevance: 'Very high',
          disposition: 'GAP',
          gapId: 'GAP-AVOIDABLE-ED',
          sourceIncentiveNote: 'AHRQ HCUP microdata RESTRICTED; no free KY Medicaid avoidable-ED rate in pack',
          primarySourceKeys: ['ahrqHcup', 'ahrqQi', 'kyDms'],
        },
        {
          id: 'f-rural-distance',
          focusId: 'access',
          title: 'Average distance to care (rural)',
          magnitude: 'Gap — claims geo',
          magnitudeValue: 0,
          budgetRelief: 0.45,
          careResults: 0.58,
          freshness: 'Provisional',
          confidence: 0.15,
          constituencyRelevance: 'Very high',
          disposition: 'GAP',
          gapId: 'GAP-RURAL-DISTANCE',
          sourceIncentiveNote:
            'Miles-to-care remains Gap (claims geo). KY Primary Care HPSA county designation counts are loaded as M-020 from public HRSA AHRF (CY2017–CY2025).',
          primarySourceKeys: ['hrsaRural', 'kyRuralHealth', 'hrsaAreaHealth'],
        },
        {
          id: 'f-mco-withholding',
          focusId: 'mco',
          title: 'MCO EQRO / evaluation accountability (themes)',
          magnitude: 'Themes published — $ Gap',
          magnitudeValue: 0.5,
          budgetRelief: 0.52,
          careResults: 0.5,
          freshness: 'Recent',
          confidence: 0.6,
          constituencyRelevance: 'Medium',
          disposition: 'REAL',
          measureId: 'M-014',
          gapId: 'GAP-MCO-WITHHOLDING-DOLLARS',
          sourceIncentiveNote: 'Evaluation PDF is REAL meta; withholding dollars remain Gap',
          primarySourceKeys: ['kyDmsManagedCare', 'medicaidManagedCare'],
        },
        {
          id: 'f-hd67',
          focusId: 'district',
          title: 'Kenton County enrollment (HD-67 adjacent public substitute)',
          magnitude: 'Gap for HD spend; county REAL',
          magnitudeValue: 0.4,
          budgetRelief: 0.35,
          careResults: 0.48,
          freshness: 'Recent',
          confidence: 0.55,
          constituencyRelevance: 'Very high',
          disposition: 'GAP',
          gapId: 'GAP-HD-EXPENDITURE',
          relatedCountyId: 'kenton',
          sourceIncentiveNote: 'No public House-district expenditure SoT; county membership is the public substitute',
          primarySourceKeys: ['kyDms', 'kyOpenData', 'censusAcs'],
        },
        {
          id: 'f-pending-maternal',
          focusId: 'bill',
          title: 'Pending maternal / postpartum Medicaid legislation (LRC)',
          magnitude: `${pack.legislation.length} touchpoints`,
          magnitudeValue: 0.45,
          budgetRelief: 0.48,
          careResults: 0.7,
          freshness: 'Provisional',
          confidence: 0.55,
          constituencyRelevance: 'High',
          disposition: 'REAL',
          measureId: 'M-028',
          sourceIncentiveNote: 'Curated from Kentucky Legislative Record — verify committee status',
          primarySourceKeys: ['kyLegislatureRecord', 'cmsMaternalQuality', 'kyDms'],
        },
      ];
      const optionPacks = [
        {
          id: 'pack-pc-pharmacy-rural',
          title: 'Primary-care access + pharmacy stewardship + rural follow-up',
          tags: ['budget', 'care', 'access'],
          axes: { budget: 0.78, care: 0.82, access: 0.8, mco: 0.55, political: 0.74 },
          budgetWin: 'Frames pharmacy pressure using federal published drug spend',
          careWin: 'Ties maternal Core Set indicator to access examination',
          politicalWin: 'District-adjacent county enrollment + bipartisan oversight framing',
          whoGains: 'Members in high-enrollment counties; postpartum cohorts in published measures',
          whoMayBearCost: 'Incomplete until encounter DUA fills cost-driver Gaps',
          timeHorizon: 'Session levers now; outcomes lagged to Core Set publish',
          levers: ['MCO network adequacy standards', 'Value-based maternal measure', 'Formulary / rebate scrutiny'],
          failureModes: ['Provider capacity gaps', 'Transportation barriers', 'Encounter data lag'],
          trustCaveats: 'Examination package — avoidable-ED and miles-to-care remain labeled Gaps',
          evidenceLevel: 'Emerging',
        },
        {
          id: 'pack-mco-bh',
          title: 'MCO accountability + published evaluation themes',
          tags: ['mco', 'care', 'budget'],
          axes: { budget: 0.7, care: 0.76, access: 0.62, mco: 0.88, political: 0.68 },
          budgetWin: 'Uses evaluation meta without inventing withholding dollars',
          careWin: 'Adult/Child Core Set rates as quality examination anchors',
          politicalWin: 'Contract accountability framing from public DMS PDFs',
          whoGains: 'Oversight users needing published MCO accountability evidence',
          whoMayBearCost: 'MCOs — only where public evaluation themes apply',
          timeHorizon: 'Next contract cycle / mid-year amendment window',
          levers: ['Quality withholding measures (Gap $)', 'Network adequacy for BH', 'EQRO report review'],
          failureModes: ['Workforce shortages', 'Incomplete encounter data'],
          trustCaveats: 'Withholding dollar outcomes are Gap — do not treat themes as $ facts',
          evidenceLevel: 'Early',
        },
        {
          id: 'pack-district-brief',
          title: 'District-ready stewardship brief with county public substitutes',
          tags: ['district', 'budget', 'bill'],
          axes: { budget: 0.65, care: 0.6, access: 0.58, mco: 0.5, political: 0.9 },
          budgetWin: 'Frames growth using federal expenditure + county enrollment',
          careWin: 'Links LRC maternal bills to published postpartum indicator',
          politicalWin: 'Colleague one-pager with explicit Gap honesty on HD spend',
          whoGains: 'Legislators needing defensible public-data narratives',
          whoMayBearCost: 'None direct — communication packing only',
          timeHorizon: 'This session',
          levers: ['Consideration Brief export', 'County peer benchmarks', 'LRC bill notes'],
          failureModes: ['Overclaiming causality', 'Stale Scorecard lag'],
          trustCaveats: 'HD expenditure is Gap; Kenton county enrollment is the public substitute',
          evidenceLevel: 'Process',
        },
      ];
      const findingsPayload = {
        schema: 'decisionpro/blender-findings-real/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        note: 'Blender findings — REAL or GAP disposition; no synthetic magnitudes',
        findings,
        optionPacks,
        legislation: pack.legislation,
      };
      await fs.writeFile(
        path.join(ALP, 'blenderFindings.real.js'),
        writeJs('blender', 'BLENDER_REAL', findingsPayload),
        'utf8',
      );
      this.FilesWritten.push('blenderFindings.real.js');
      // Every OFR adapter (OFR-01..07) lands facts straight to REAL load_history
      // without ever appearing in pack.landingMeasures (that array is scoped to
      // the base M-xxx measure pipeline) — so those FromSysIDs would otherwise
      // show CATALOGUED even after a fully reconciled REAL load. Query load
      // history directly instead of hardcoding a per-FromSysID list.
      const loadedFromSysIdsQ = await this.client.query<{ from_sys_id: string }>(
        `SELECT DISTINCT dr.from_sys_id
         FROM bw_ctl.load_history lh
         JOIN bw_ctl.data_request dr ON dr.data_request_id = lh.data_request_id
         WHERE lh.load_class='REAL' AND lh.status='SUCCEEDED'`,
      );
      const loadedFromSysIds = new Set(loadedFromSysIdsQ.rows.map((r) => r.from_sys_id));

      const sourcesPayload = {
        schema: 'decisionpro/authoritative-sources/v1',
        generatedAt: new Date().toISOString(),
        note: 'Authoritative sources catalogue for DecisionPro UI — links + TOS + load status',
        sources: SOURCE_SYSTEMS.filter((s) => s.from_sys_id !== 'TEST_FIXTURE_PACK').map((s) => {
          const measureHits = pack.landingMeasures.filter((m) => m.fromSysId === s.from_sys_id);
          const fileHref =
            measureHits.find((m) => m.sourceUri && m.sourceUri !== s.base_uri)?.sourceUri || undefined;
          const blockReason = 'block_reason' in s ? String((s as { block_reason?: string }).block_reason || '') : '';
          const unblockNeed = 'unblock_need' in s ? String((s as { unblock_need?: string }).unblock_need || '') : '';
          return {
            fromSysId: s.from_sys_id,
            publisher: s.publisher,
            tosGrade: s.tos_grade,
            href: s.base_uri,
            ...(fileHref ? { fileHref } : {}),
            attributionNotes: s.attribution_notes,
            paidFollowOnTodo: s.paid_follow_on_todo,
            ...(blockReason ? { blockReason } : {}),
            ...(unblockNeed ? { unblockNeed } : {}),
            loadStatus: measureHits.length || s.from_sys_id === 'CMS_DATA_MEDICAID_ENR' || s.from_sys_id === 'KY_DMS_MCO_CONTRACTS' || loadedFromSysIds.has(s.from_sys_id)
              ? 'LOADED'
              : s.tos_grade === 'RESTRICTED'
                ? 'BLOCKED'
                : 'CATALOGUED',
            measureIds: [...new Set(measureHits.map((m) => m.measureId))],
            asOfDate:
              [...measureHits].sort((a, b) => a.asOfDate.localeCompare(b.asOfDate)).at(-1)?.asOfDate ||
              pack.asOfDate,
          };
        }),
      };
      // Mark enrollment + MCO as loaded always after gate
      for (const s of sourcesPayload.sources) {
        if (s.fromSysId === 'CMS_DATA_MEDICAID_ENR' || s.fromSysId === 'KY_DMS_MCO_CONTRACTS') {
          s.loadStatus = 'LOADED';
        }
      }
      await fs.writeFile(
        path.join(ALP, 'authoritativeSources.js'),
        writeJs('sources', 'AUTHORITATIVE_SOURCES', sourcesPayload),
        'utf8',
      );
      this.FilesWritten.push('authoritativeSources.js');

      const periodMap = new Map<string, { id: string; label: string; shortLabel: string; sort: number }>();
      const addPeriod = (id: string, label: string, shortLabel: string, sort: number) => {
        if (!id || periodMap.has(id)) return;
        periodMap.set(id, { id, label, shortLabel, sort });
      };
      addPeriod('latest', 'Latest available', 'Latest', 9000);
      addPeriod('fy', 'Fiscal year (published)', 'FY', 9010);
      addPeriod('cy', 'Calendar year (generic)', 'CY', 9020);
      for (const m of pack.landingMeasures) {
        const pid = m.periodId || '';
        if (pid.startsWith('ffy')) {
          const y = pid.slice(3);
          const my = Number(y) - 1;
          addPeriod(
            pid,
            `CMS Core Set FFY ${y} reporting (MY ${my})`,
            `FFY ${y}`,
            Number(y) || 2000,
          );
        } else if (pid.startsWith('cy')) {
          const y = pid.slice(2);
          addPeriod(pid, `ACS / calendar CY${y}`, `CY${y.slice(2)}`, Number(y) || 2000);
        } else if (pid.startsWith('ky')) {
          const ym = pid.slice(2);
          const labelYm = ym.length === 6 ? `${ym.slice(0, 4)}-${ym.slice(4)}` : ym;
          addPeriod(pid, `DMS county ${labelYm}`, `KY ${labelYm}`, Number(ym) || 3000);
        }
      }
      for (const row of enrollQ.rows.filter((r) => r.measure_id === 'M-001')) {
        const prov = row.provenance_json || {};
        const periodYm = prov.periodYm || row.as_of_date.replace(/-/g, '').slice(0, 6);
        const period = prov.periodId || `pi${periodYm}`;
        const y = periodYm.slice(0, 4);
        const mo = periodYm.slice(4, 6);
        addPeriod(period, `CMS PI ${y}-${mo}`, `PI ${y}-${mo}`, Number(periodYm) || 4000);
      }
      const periodsPayload = {
        schema: 'decisionpro/periods-real/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        note: 'Evidence Room period filter catalog from REAL loads — not hand-maintained PI months.',
        periods: [...periodMap.values()].sort((a, b) => a.sort - b.sort || a.id.localeCompare(b.id)),
      };
      await fs.writeFile(
        path.join(ALP, 'periods.real.js'),
        writeJs('periods', 'PERIODS_REAL', periodsPayload),
        'utf8',
      );
      this.FilesWritten.push('periods.real.js');

      const jsonSide = path.join(config.psaRoot, '..', 'exports', 'hydration-bundles.json');
      await fs.mkdir(path.dirname(jsonSide), { recursive: true });
      await fs.writeFile(
        jsonSide,
        JSON.stringify({ roomPayload, gapPayload, findingsPayload, sourcesPayload, periodsPayload }, null, 2),
        'utf8',
      );
      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }
}
