import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { MEASURES, SOURCE_SYSTEMS } from '../catalog/seedCatalog.js';
import { REPO_ROOT } from '../config.js';
import {
  CheckAccurateLandingNumbers,
  type AccuracyResult,
} from './CheckAccurateLandingNumbers.js';

const ALP = path.join(REPO_ROOT, 'wireframe V1', 'app', 'src', 'data', 'alp');

const PROCESS = {
  name: 'Source Reconciliation',
  businessAction: 'Reconcile Published Measures',
  description:
    'Independent verification that dashboard and cube magnitudes match the owning published source aggregates, with lineage and definition alignment. Distinct from the Accuracy Gate, which controls pipeline release.',
  distinctFromAccuracyGate:
    'The Accuracy Gate owns TEST → purge → REAL → release. Source Reconciliation owns legitimacy and accuracy of numbers; it runs inside the gate and after every REAL refresh or upload.',
  steps: [
    {
      id: 'lineage',
      title: 'Confirm the lineage',
      summary:
        'Walk each number from the screen back through the cube, Detail DSO, and PSA landing file to the LoadHistory record that cites the published source, period, and retrieval time.',
    },
    {
      id: 'owning-source',
      title: 'Match the owning published source',
      summary:
        'Re-open the same government extract that owns the measure and compare it to the warehouse value within documented rounding rules.',
    },
    {
      id: 'definition',
      title: 'Check definition, grain, and period',
      summary:
        'Verify that the numerator, denominator, population, geography, and reporting period match the measure catalog.',
    },
    {
      id: 'concordance',
      title: 'Review related sources (advisory)',
      summary:
        'Optionally compare related authoritative publications for context. Methodology or lag differences here do not by themselves pass or fail the accuracy claim.',
      advisory: true,
    },
    {
      id: 'record',
      title: 'Record the outcome',
      summary:
        'Record pass, fail, or intentional gap per measure with citations. Failures must be repaired and rechecked before an accuracy claim is allowed.',
    },
  ],
  flow: {
    nodes: [
      { id: 'refresh', label: 'REAL refresh or upload' },
      { id: 'gate', label: 'Accuracy Gate (cutover)' },
      { id: 'recon', label: 'Source Reconciliation' },
      { id: 'claim', label: 'Accuracy claim allowed' },
      { id: 'repair', label: 'Repair, reload, recheck' },
    ],
    edges: [
      { from: 'refresh', to: 'recon' },
      { from: 'gate', to: 'recon' },
      { from: 'recon', to: 'claim', label: 'pass' },
      { from: 'recon', to: 'repair', label: 'fail' },
      { from: 'repair', to: 'recon' },
    ],
  },
};

function writeJs(exportName: string, payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * Source Reconciliation last-run + process description for Authoritative sources UI.
 */
export const ${exportName} = ${JSON.stringify(payload, null, 2)};
`;
}

function measureMeta(measureId: string) {
  const base = measureId.replace(/-SERIES$|-HIST$/, '');
  return MEASURES.find((m) => m.measure_id === base) || MEASURES.find((m) => m.measure_id === measureId);
}

/**
 * Business Action: ExportSourceReconciliationForUi
 * Runs owning-source checks and exports last-run results for the legislative UI.
 */
export class ExportSourceReconciliationForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = path.join(ALP, 'sourceReconciliation.js');
  Results: AccuracyResult[] = [];
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';
  CheckCount = 0;

  constructor(private client: pg.PoolClient) {}

  async Run(trigger: string = 'export-ui') {
    if (this.Status !== 'INITIAL') return;
    try {
      const check = new CheckAccurateLandingNumbers(this.client);
      await check.Run();
      this.Results = check.Results;
      this.CheckCount = check.Results.length;
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';
      await this.writePayload(trigger, check);
      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }

  /** Write UI export from an already-executed CheckAccurateLandingNumbers instance. */
  async WriteFromCheck(check: CheckAccurateLandingNumbers, trigger: string = 'accuracy-check') {
    if (this.Status !== 'INITIAL') return;
    try {
      this.Results = check.Results;
      this.CheckCount = check.Results.length;
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';
      await this.writePayload(trigger, check);
      this.Status = 'SUCCEEDED';
    } catch (e) {
      this.Status = 'FAILED';
      this.ErrorMessage = e instanceof Error ? e.message : String(e);
    }
  }

  private async writePayload(trigger: string, check: CheckAccurateLandingNumbers) {
    const landing = await this.client.query<{
      measure_id: string;
      display_value: string;
      numeric_value: string | null;
      as_of_date: string;
      from_sys_id: string;
      load_history_id: string;
      provenance_json: {
        sourceUri?: string;
        sourcePageUri?: string;
        periodYm?: string;
        periodId?: string;
      } | null;
    }>(
      `SELECT DISTINCT ON (measure_id)
         measure_id, display_value, numeric_value::text, as_of_date::text,
         from_sys_id, load_history_id, provenance_json
       FROM bw_cube.cube_exec_landing
       WHERE load_class = 'REAL'
       ORDER BY measure_id, as_of_date DESC, load_history_id DESC`,
    );
    const byMeasure = new Map(landing.rows.map((r) => [r.measure_id, r]));
    const sourceById = new Map<string, (typeof SOURCE_SYSTEMS)[number]>(
      SOURCE_SYSTEMS.map((s) => [s.from_sys_id, s]),
    );

    const results = check.Results.map((r) => {
      const meta = measureMeta(r.measure_id);
      const cube = byMeasure.get(r.measure_id.replace(/-SERIES$|-HIST$/, '')) || byMeasure.get(r.measure_id);
      const fromSysId = cube?.from_sys_id || meta?.sources?.[0] || null;
      const src = fromSysId ? sourceById.get(fromSysId) : undefined;
      const prov = cube?.provenance_json || {};
      return {
        measureId: r.measure_id,
        name: meta?.name || r.measure_id,
        ok: r.ok,
        result: r.ok ? 'PASS' : 'FAIL',
        expected: r.expected,
        actual: r.actual,
        detail: r.detail,
        fromSysId,
        asOfDate: cube?.as_of_date || null,
        loadHistoryId: cube?.load_history_id || null,
        sourceUri: prov.sourceUri || null,
        sourcePageUri: prov.sourcePageUri || src?.base_uri || null,
        publisher: src?.publisher || null,
      };
    });

    const passed = results.filter((r) => r.ok).length;
    const failed = results.length - passed;
    const claimAllowed = failed === 0 && check.Status === 'SUCCEEDED';

    const headlineIds = ['M-001', 'M-002', 'M-007'];
    const executiveBullets = headlineIds
      .map((id) => results.find((r) => r.measureId === id))
      .filter(Boolean)
      .map((r) => ({
        measureId: r!.measureId,
        name: r!.name,
        displayValue: r!.actual,
        expected: r!.expected,
        result: r!.result,
        fromSysId: r!.fromSysId,
        sourcePageUri: r!.sourcePageUri,
        sourceUri: r!.sourceUri,
      }));

    const payload = {
      schema: 'decisionpro/source-reconciliation/v1',
      generatedAt: new Date().toISOString(),
      note: 'Last Source Reconciliation run for Authoritative sources UI. Owning-source reconcile is pass/fail; concordance is advisory.',
      process: PROCESS,
      lastRun: {
        ranAt: new Date().toISOString(),
        trigger,
        overallStatus: this.ReconciliationStatus,
        claimAllowed,
        checkError: check.Status === 'SUCCEEDED' ? null : check.ErrorMessage || null,
        summary: {
          checksTotal: results.length,
          checksPassed: passed,
          checksFailed: failed,
          claimAllowed,
          executiveBullets,
        },
        results,
      },
    };

    await fs.mkdir(ALP, { recursive: true });
    await fs.writeFile(this.ExportPath, writeJs('SOURCE_RECONCILIATION', payload), 'utf8');
  }
}
