import fs from 'node:fs/promises';
import path from 'node:path';
import type pg from 'pg';
import { config } from '../config.js';
import { CheckOrganizationCrosswalkNumbers } from './CheckOrganizationCrosswalkNumbers.js';

type MetricRow = { metric_id: string; state_code: string; metric_label: string; numeric_value: string | null; display_value: string; unit: string; as_of_date: string };
type ExactRow = { assertion_id: string; state_code: string; match_method: string; left_identifier_type: string; left_identifier_value: string; right_identifier_type: string; right_identifier_value: string; confidence: string; evidence_citation: string; from_sys_ids: string[] };
type InferredRow = ExactRow;
type DisagreementRow = { disagreement_id: string; state_code: string; uei: string; sam_name: string; usaspending_name: string; similarity_score: string; status: string };

function generatedModule(payload: unknown) {
  return `/**
 * Generated by XenoDroid BW export — do not hand-edit.
 * OFR-02 organization identity crosswalk spine, state-neutral (KY + FL).
 * exactAssertions and inferredAssertions are SEPARATE collections by design:
 * an inferred match is a review candidate and must never be rendered or
 * treated as confirmed identity.
 */
export const ORGANIZATION_CROSSWALK = ${JSON.stringify(payload, null, 2)};
`;
}

/**
 * Business Action: ExportOrganizationCrosswalkForUi
 * Exports per-state crosswalk coverage stats (method breakdown), the exact
 * and inferred assertion collections (kept structurally separate), and the
 * open SAM-vs-USAspending disagreement queue.
 */
export class ExportOrganizationCrosswalkForUi {
  Status: 'INITIAL' | 'SUCCEEDED' | 'FAILED' = 'INITIAL';
  ErrorMessage = '';
  ExportPath = config.organizationCrosswalkExportPath;
  StateCount = 0;
  ReconciliationStatus: 'PASS' | 'FAIL' = 'FAIL';

  constructor(private client: pg.PoolClient) {}

  async Run() {
    if (this.Status !== 'INITIAL') return;
    try {
      const metrics = await this.client.query<MetricRow>(
        `SELECT DISTINCT ON (metric_id, state_code) metric_id, state_code, metric_label, numeric_value::text, display_value, unit, as_of_date::text
         FROM bw_cube.cube_crosswalk_metric WHERE load_class='REAL' ORDER BY metric_id, state_code, as_of_date DESC`,
      );
      const exact = await this.client.query<ExactRow>(
        `SELECT assertion_id, state_code, match_method, left_identifier_type, left_identifier_value,
           right_identifier_type, right_identifier_value, confidence::text, evidence_citation, from_sys_ids
         FROM bw_ctl.organization_crosswalk_exact WHERE load_class='REAL' ORDER BY state_code, assertion_id`,
      );
      const inferred = await this.client.query<InferredRow>(
        `SELECT assertion_id, state_code, match_method, left_identifier_type, left_identifier_value,
           right_identifier_type, right_identifier_value, confidence::text, evidence_citation, from_sys_ids
         FROM bw_ctl.organization_crosswalk_inferred WHERE load_class='REAL' ORDER BY state_code, assertion_id`,
      );
      const disagreements = await this.client.query<DisagreementRow>(
        `SELECT disagreement_id, state_code, uei, sam_name, usaspending_name, similarity_score::text, status
         FROM bw_ctl.organization_crosswalk_disagreement WHERE load_class='REAL' ORDER BY state_code, disagreement_id`,
      );

      const check = new CheckOrganizationCrosswalkNumbers(this.client);
      await check.Run();
      this.ReconciliationStatus = check.Status === 'SUCCEEDED' ? 'PASS' : 'FAIL';

      const byState: Record<string, unknown> = {};
      for (const state of config.ofrStates) {
        const stateMetrics = Object.fromEntries(
          metrics.rows.filter((m) => m.state_code === state).map((m) => [m.metric_id, {
            label: m.metric_label, numericValue: m.numeric_value == null ? null : Number(m.numeric_value),
            displayValue: m.display_value, unit: m.unit, asOfDate: m.as_of_date,
          }]),
        );
        const stateExact = exact.rows.filter((r) => r.state_code === state);
        const stateInferred = inferred.rows.filter((r) => r.state_code === state);
        const methodBreakdown = {
          exactPublished: stateExact.filter((r) => r.match_method === 'exact-published').length,
          exactDerived: stateExact.filter((r) => r.match_method === 'exact-derived').length,
          inferred: stateInferred.length,
        };
        byState[state] = {
          state,
          coverageNote: 'organization_crosswalk_exact and organization_crosswalk_inferred are separate collections. No inferred assertion is ever presented as confirmed identity — every inferredAssertions row below carries a confidence score and must be labeled a review candidate wherever it is rendered.',
          metrics: stateMetrics,
          methodBreakdown,
          exactAssertions: stateExact.map((r) => ({
            assertionId: r.assertion_id, method: r.match_method, left: { type: r.left_identifier_type, value: r.left_identifier_value },
            right: { type: r.right_identifier_type, value: r.right_identifier_value }, confidence: Number(r.confidence),
            evidence: r.evidence_citation, sources: r.from_sys_ids,
          })),
          inferredAssertions: stateInferred.map((r) => ({
            assertionId: r.assertion_id, method: 'inferred', left: { type: r.left_identifier_type, value: r.left_identifier_value },
            right: { type: r.right_identifier_type, value: r.right_identifier_value }, confidence: Number(r.confidence),
            evidence: r.evidence_citation, sources: r.from_sys_ids, reviewCandidateOnly: true,
          })),
          disagreementQueue: disagreements.rows.filter((r) => r.state_code === state).map((r) => ({
            disagreementId: r.disagreement_id, uei: r.uei, samName: r.sam_name, usaSpendingName: r.usaspending_name,
            similarity: Number(r.similarity_score), status: r.status,
          })),
        };
        this.StateCount += 1;
      }

      const payload = {
        schema: 'decisionpro/organization-crosswalk/v1',
        generatedAt: new Date().toISOString(),
        loadClass: 'REAL',
        groundingCorrection: 'Neither the SAM.gov Entity Management API (Director-provisioned key) nor USAspending exposes EIN at this access tier, verified live 2026-08-31. The only genuine same-record ("exact-published") cross-identifier fact available is NPPES (NPI + embedded state Medicaid ID). All other links are computed name/address matches, classified exact-derived or inferred.',
        reconciliation: { status: this.ReconciliationStatus, claimAllowed: this.ReconciliationStatus === 'PASS', checks: check.Results },
        byState,
      };

      await fs.mkdir(path.dirname(this.ExportPath), { recursive: true });
      await fs.writeFile(this.ExportPath, generatedModule(payload), 'utf8');
      this.Status = 'SUCCEEDED';
    } catch (error) {
      this.Status = 'FAILED';
      this.ErrorMessage = error instanceof Error ? error.message : String(error);
    }
  }
}
